README.md
ruby/core.rb
ruby/mal_readline.rb
ruby/printer.rb
ruby/reader.rb
ruby/step0_repl.rb
ruby/step1_read_print.rb
ruby/step2_eval.rb
ruby/step3_env.rb
ruby/step4_if_fn_do.rb
ruby/step5_tco.rb
ruby/step6_file.rb
ruby/step7_quote.rb
ruby/step8_macros.rb
ruby/step9_try.rb
ruby/stepA_interop.rb
ruby/types.rb

Hey! 
This patch makes mal run on modern rubies. I've tested it on 2.1 and 2.2, but it should work on anything from 1.9 on. It also fixes a crash if the history file doesn't exist.
Ruby 1.8 will no longer work. Hopefully that won't be a problem, 1.8.7 is long retired.

Ruby: Updated for Ruby 1.9+

---

rust/Cargo.toml
rust/src/lib.rs
rust/src/reader.rs

I fixed the bug in Rust's `regex` library and things seem to be working great now. Even through `regex` is based on RE2, I didn't have to change your regex at all. :-)
I ran this to test:
```bash
make perf^rust
make MAL_IMPL=rust test^mal
```
The first passes and the second passes all tests except for 1, but it looks like the same failing test from #26.

Replace `pcre` with Rust-implemented regex crate (based on RE2).

---

python/step0_repl.py
runtest.py

Two things:
* a syntax error in 'step0_repl.py' (see below) fixed
```bash
$ python --version
Python 3.4.3
$ cd python/
$ python step0_repl.py
File "step0_repl.py", line 14
exec compile(ast, '', 'single') in globals()
^
SyntaxError: invalid syntax
```
* the test script, 'runtest.py', now made compatible with Python 3 (initially getting errors about ``print`` missing parentheses, and ``bytes``/``str`` decoding/encoding)
Now, I can run Mal tests in both Python 2 and 3. Also tested with Ruby and Clojure.
Thanks for reviewing.

Compatibility with Python 3

---

process/guide.md

another minor typo in the guide; `step2_env.qx` should've been `step3_env.qx`

guide: incorrect filename fixed

---

tests/step3_env.mal

I noticed that when I implemented step 3 with an environment that didn't have an "outer" reference, all the tests passed.  Here are some simple tests that check if outer is functioning.

Add outer tests to step3_env.mal

---

tests/step9_try.mal

I had a bug in my apply core function. It worked for core functions, but
not for user-defined functions.
This bug escaped direct testing, but caused problems in self-host
testing.
Here's a couple of simple test cases that catch those errors.

Step 9 apply tests test user fns as well as core

---

tests/step9_try.mal

My reader complains if there is extra input after the top-level
read_form, so this test was inadvertently failing for me.

Remove extra ) from step9 test snippet

---

perl/types.pm
tests/stepA_mal.mal

I stumbled over this typo while looking through the Perl implementation.
Thought I might as well add a test case to catch similar errors.

Test case & fix for typo in Perl _clone implementation

---

tests/step9_try.mal

While it still needs a little work, my C++ implementation now passes all[1] of the self-hosting tests (!)
The only bug I had between passing stepA, and then passing the self-hosting tests was that my apply implementation insisted on a list, and needed to be relaxed to accept any sequence.
Here's a couple of (apply f vector) tests which catch that bug.
[1] All but one. `(read-string ";; comment")` in the step 6 test gives me a strange python IO error from runtest.py. I need to look further into that one - it works fine if I type it in manually.

Step 9 test cases for apply on vectors

---

coffee/core.coffee

The previous version was requiring the `js` directory's version of `node_readline`, which crashes if `npm install` has not been run in that directory.
This commit uses the file located in the `coffee` directory. Running `make test^coffee` passes.

Require correct node_readline file

---

README.md
nim/Makefile
nim/mal.nimble
nim/reader.nim

- Use re from standard library instead of nre
- Allow make -j4
- Rebuild binaries after source changed
I guess it's better/easier not to use an external regexp library. All tests still pass.

Make Nim implementation a bit nicer

---

process/guide.md

While implementing with Crystal,  I found some mistakes.  I fixed them.

guide: fix missing escape and typo

---

c/readline.c

When the editline was used instead of the readline, the history function of C didn't work as intended.
It was caused like below.
- segmentation fault if a history is empty.
- incorrect line was added to a history file.

fix history function of C

---

cs/step6_file.cs
cs/step7_quote.cs
cs/step8_macros.cs
cs/step9_try.cs
cs/stepA_mal.cs

The arguments handling was incorrect like below.
- step6 to step9  
`*ARGV*` was right but the filename of `load-file` was wrong.
- stepA  
The filename of `load-file` was right but `*ARGV*` includes the
filename.

C#: fix arguments handling

---

elixir/lib/mix/tasks/step6_file.ex
elixir/lib/mix/tasks/step7_quote.ex
elixir/lib/mix/tasks/step8_macros.ex
elixir/lib/mix/tasks/step9_try.ex
elixir/lib/mix/tasks/stepA_mal.ex

As for the `iex -S mix stepA_mal` vs `mix stepA_mal` issue:
> The reason I'm running it with `iex -S` is to be able to use `iex`'s readline functionality, as there's no readline wrapper available for Elixir. If you want to I'll change it to just `mix stepA_mal` which compiles if necessary and runs the REPL, albeit without history/parenthesis matching and so on.
What do you think?

Only print Elixir header info in REPL mode

---

.gitignore

A seperate nimcache folder was being generated for each step with the
name of the step appended to nimcache, like nimcache-step0_repl and so
was not being ignored by git.
This change will prevent git from tracking
any folder with name starting with nimcache in the nim directory.

Changed nim/nimcache to nim/nimcache* in .gitignore

---

README.md
crystal/core.cr

Now all tests are passed in my local environment (OS X 10.9).

Crystal: Fixed missing method error for Crystal 0.8.0

---

erlang/rebar.config
erlang/src/printer.erl
erlang/src/reader.erl

Properly read \\n and convert to a newline, and when printing with
readability enabled, convert the newline back to \\n.
Add support for Erlang R18, which was nothing more than tweaking the
requirements in the rebar.config file.
Fixes #100
make test^erlang passes

Fix reading/printing of escaped characters

---

Makefile
README.md
tcl/Dockerfile
tcl/Makefile
tcl/core.tcl
tcl/env.tcl
tcl/mal_readline.tcl
tcl/printer.tcl
tcl/reader.tcl
tcl/step0_repl.tcl
tcl/step1_read_print.tcl
tcl/step2_eval.tcl
tcl/step3_env.tcl
tcl/step4_if_fn_do.tcl
tcl/step5_tco.tcl
tcl/step6_file.tcl
tcl/step7_quote.tcl
tcl/step8_macros.tcl
tcl/step9_try.tcl
tcl/stepA_mal.tcl
tcl/tests/stepA_mal.mal
tcl/types.tcl

Full Tcl implementation of mal - passes all tests and self-hosting tests. It requires Tcl 8.6 because I use `oo::class`. It includes readline support via tclreadline (if available) and very basic Tcl "integration" with the `tcl*` form (see `tcl/tests/stepA_mal.mal` for examples).
One issue: this implementation leaks memory - environments are not really deleted. Tcl has no garbage collection, and new objects (in our case, new Env objects) are never deleted unless explicitly destroyed. The following mal program causes the implementation to be killed by the Linux OOM killer:
```
(def! rec (fn* () (rec)))
(rec)
```
I noticed this is also a proglem of the C implementation, but does not occur in the Ruby implementation (the Ruby GC kicks into work correctly).
I think this can be solved for Tcl …

Tcl implementation

---

tests/step9_try.mal

No one was testing that the `=` function works correctly on hash-maps. I introduce this test in step9 together with `hash-map`, `map?` etc.

tests: step9: add hash-map equality tests

---

examples/equality.mal

(as discussed in #112)
Implementations that don't have proper native comparison of hash-maps and sequences can load examples/equality.mal for a pure-mal implementation.
The file automatically detects if the native `=` works OK for hashes and sequences. If yes, it does nothing; if not, it redefines `=` as `mal-equal?`, which is the pure-mal implementation.
Example (perl mal as of Nov 2015 doesn't support hash-map equality):
```
$ perl stepA_mal.pl
Mal [perl]
user> (= {:a 11 :b 22} (hash-map :b 22 :a 11))
Error: TODO: Hash map comparison
user> (= {:a 11 :b 22} (hash-map :a 11))
Error: TODO: Hash map comparison
user> (load-file "../examples/equality.mal")
equality.mal: Replaced = with pure mal implementation
nil
user> (= {:a 11 :b 22} (hash-map :b 22 :a 11))
true
user> (= {:a 11 :b 22} …
```

add examples/eqaulity.mal

---

ocaml/core.ml
ocaml/types.ml

Define a `mal_equal` recursive function for testing nested data-structures (list/vector/hashmap) for equality.

ocaml: fix hash equality

---

docs/TODO
lua/Dockerfile
lua/core.lua

We install the luasocket rock to use its `socket.gettime()` function which returns sub-second resolution timestamps.

lua: fix time-ms to return actual millisecond resolution timestamp

---

tests/step4_if_fn_do.mal

(as discussed in #116)
For example, these nested list/vector tests currently soft-fail in the guile implementation.

tests: add soft tests for nested vector/list equality in step 4

---

guile/core.scm

(As part of #116 and #123)
Probably could use some better scheme styling. For example, maybe `_equal-lists?` and `_equal-hash-tables?` should be defined *inside* `_equal?` ? I'm not sure what's the best style here. I'll be glad to fix with some directions.

guile: fix equality of hash-maps and lists/vectors

---

nim/reader.nim
tests/step1_read_print.mal

The input string `(prn "abc` caused the nim implementaion (from step1
onwards) to enter an endless loop in tokenize (which eventually caused
out-of-memory).
The fix verfies that indeed the regex matches a non-empty substring
before adding that substring as a token.

nim: fix tokenizer endless loop (and out-of-memory) on bad input

---

README.md
docs/FAQ.md
process/guide.md

Addresses #113 and incidentally,  #30 
I thought that the `make foo^bar` pattern appeared in too many files in this project to warrant putting a disclaimer in each file for zsh users.

quoted all make args in documentation for zsh compatibility

---

examples/memoize.mal

Adapted from the Clojure example of atoms: http://clojure.org/atoms
Benchmark:
```
$ cd examples
$ ../nim/mal memoize.mal
fib N= 32 : without memoization:
"Elapsed time: 14402 msecs"
fib N= 32 : with memoization:
"Elapsed time: 1 msecs"
```

examples: add memoize.mal as a usage example for atoms

---

Makefile
README.md

From README.md:
----
* To start the REPL of an implementation in a specific step:
```
make "repl^IMPL^stepX"
make "repl^ruby^step3"
make "repl^ps^step4"
```
* If you omit the step, then `stepA` is used:
```
make "repl^IMPL"
make "repl^ruby"
make "repl^ps"
```
* To start the REPL of the self-hosted implementation, specify `mal` as the
REPL implementation and use the `MAL_IMPL` make variable to change the
underlying host language (default is JavaScript):
```
make MAL_IMPL=IMPL "repl^mal^stepX"
make "repl^mal^step2"   # js is default
make MAL_IMPL=ruby "repl^mal^step2"
make MAL_IMPL=python "repl^mal"
```

Makefile: add REPL invocation rules

---

runtest.py

Gather and re-print failed test cases at the end of the test suite. This saves the trouble of scanning up the 157 test cases and finding the two failures.
Example output:
```
...
...
Testing vector parameter lists
TEST: ( (fn* [] 4) ) -> ['',4] -> SUCCESS
TEST: ( (fn* [f x] (f x)) (fn* [a] (+ 1 a)) 7) -> ['',8] -> SUCCESS
-------- Soft tests --------
(when most implementations will implement these tests correctly this section
will be modified to hard failures)
Nested vector/list equality
TEST: (= [(list)] (list [])) -> ['',true] -> SUCCESS
TEST: (= [1 2 (list 3 4 [5 6])] (list 1 2 [3 4 (list 5 6)])) -> ['',true] -> SUCCESS
FAILURES:
FAILED TEST (line 314): (str (list 1 2 "abc" "\"") "def") -> ['',"(1 2 \"abc\" \"\\\"\")def"]:
Expected : '(str (list 1 2 "abc" "\\"") "def")\r\n"(1 2 …
```

runtest.py: Repeat failed test cases at the bottom

---

cpp/Core.cpp
cpp/MAL.h
cpp/Types.cpp
cpp/Types.h
cpp/step1_read_print.cpp
cpp/step2_eval.cpp
cpp/step3_env.cpp
cpp/step4_if_fn_do.cpp
cpp/step5_tco.cpp
cpp/step6_file.cpp
cpp/step7_quote.cpp
cpp/step8_macros.cpp
cpp/step9_try.cpp
cpp/stepA_mal.cpp

Here's the native swap! implementation, along with a minor env-passing cleanup.
The extra args are passed directly, there's no varargs handling like apply does. I can add that if necessary.
See #130

Native swap! implementation for cpp

---

mal.html

Due to the mixed content blocker in current versions of Firefox & Chrome the demo will not work on GitHub Pages. Loading jQuery via https will solve that issue.

Updated mal.html

---

python/core.py
python/mal_types.py
tests/step7_quote.mal

Python 2.6.6 and 2.7.10 fail the self-hosting tests of step4:
make MAL_IMPL=python test^mal^step4
Maybe we should add the self-hosting tests to Travis-CI? Also I'm not sure if Travis runs Python 2 or 3.
I reduced one of the problems to the following:
```
Mal [python]
user> "abc"
"abc"
user> (str 'abc)
"abc"
user> (= "abc" (str 'abc))
false
```
The reason is that `"abc"` is stored as python type 'unicode' whereas the result of the `str` invocation is stored as python type 'str'. The _equal_Q function sees the different types and decides the objects are not equal - this is now fixed.
I added this as a test case in step7 (in which we introduce `quote`).

python: Fix equality of unicode/normal strings in Python 2.x

---

process/guide.md

@kanaka This is minor, but I think that in this case it is meant to be `token` and not `tokens`

fix typo tokens => token

---

erlang/src/core.erl
tests/step9_try.mal

As described in #123 .
I also found another test case not covered, so I added it to the soft-tests in step9. We might see other impls soft-fail there if the map values weren't compared properly.

erlang: Fix nested list/vector/map equality

---

ocaml/step9_try.ml
ocaml/stepA_mal.ml

ocaml: Catch Mal exceptions at the top-level (both in repl and command-line file) and print the exception value clearly to stderr.
Before:
```
Mal [ocaml]
user> (throw "my error")
Erroringness!
```
After:
```
Mal [ocaml]
user> (throw "my error")
Exception: "my error"
```

ocaml: Clearer top-level exception handling

---

README.md
kotlin/Dockerfile
kotlin/src/mal/reader.kt

Kotlin 1.0 released today!
* Update Kotlin version to 1.0. All tests passed without modifying code.
* Remove one unnecessary cast
Thanks!

Bump Kotlin version to 1.0

---

ruby/core.rb
tests/step7_quote.mal

Before the fix:
```
Mal [ruby]
user> (def! a [1 2])
[1 2]
user> (concat a [3 4])
(1 2 3 4)
user> a
[1 2 3 4]
```
After the fix:
```
Mal [ruby]
user> (def! a [1 2])
[1 2]
user> (concat a [3 4])
(1 2 3 4)
user> a
[1 2]
```

ruby: concat should not modify its argument

---

js/package.json

The js dep won't compile cleanly without this bump because the old ffi version won't build properly 
(using latest Arch Linux as of Mar 14 2016, probably failing on other distros as well).  
ffi 2.0.0 builds cleanly.

Update ffi dep in js implementation

---

process/guide.md

The guide is pretty long; add TOC for easier navigation.

process/guide.md: Add TOC; fix heading levels

---

process/guide.md

Referring to the pseudocode in the process/ directory is important, but
it's easy to miss that detail when reading the guide for the first time.
Similarly, it's important to add a new Makefile in many cases, so
reformat to draw attention to that.

Tweaking text in guide.

---

Makefile

When running tests with REGRESS=1, the Makefile would not exit with
failure if an earlier step failed some tests.  Replacing `;` with `&&` in the test rule fixed this behaviour to exit with failure exitcode on the first regression failure.
How to reproduce:
1. Add a failing test to `step3_env.mal`: 
(+ 44 55)
;=>3
2. Run regression with `make REGRESS=1 test^ruby^step4`
3. This should fail when testing the step4 code with the step3 test cases and make should exit with non-zero exitcode.

Makefile: fail REGRESS=1 when earlier step fails

---

ps/stepA_mal.ps
ps/tests/stepA_mal.mal

* Simplify postscript code parsing by using the `cvx` (convert to
executable) function.
* Tweak the test cases to match reality (returns list of stack operands,
or nil if stack is empty after exec).
Here's the diff on stepA_mal.ps:
```diff
diff --git a/ps/stepA_mal.ps b/ps/stepA_mal.ps
index ae39447..5925ef3 100644
--- a/ps/stepA_mal.ps
+++ b/ps/stepA_mal.ps
@@ -146,14 +146,7 @@ end } def
ast 1 _nth env macroexpand
}{ /ps* a0 eq { %if ps*
count /stackcnt exch def
-            ast 1 _nth
-            {
-                token not { exit } if
-                exch
-                count stackcnt sub 1 roll % send leftover string to bottom
-                exec
-                count stackcnt sub -1 roll % bring leftover string to top
-            } loop
+            ast 1 _nth cvx exec
count …
```

ps: Fix ps* interop

---

swift3/Makefile
swift3/Sources/core.swift

Here are some changes to get swift3 compiling and running under OSX. There were only a few tweaks, so it should be pretty easy to vet.
I'm not sure why I had problems with the implementations of "pr-str" and "str". Perhaps it's because the compiler I'm using (DEVELOPMENT-SNAPSHOT-2016-03-24-a) is more recent than the one used for original development.

Port swift3 to OSX.

---

README.md
c/Dockerfile
c/Makefile
c/core.c
c/env.c
c/printer.c
c/reader.c
c/step0_repl.c
c/step1_read_print.c
c/step2_eval.c
c/step3_env.c
c/step4_if_fn_do.c
c/step5_tco.c
c/step6_file.c
c/step7_quote.c
c/step8_macros.c
c/step9_try.c
c/stepA_mal.c
c/types.c
c/types.h

Add the [Boehm garbage collector](http://hboehm.info/gc/) to the C implementation. The README and Dockerfile changes describe the new dependency for building.
By default, garbage collection is enabled.  You can disable the garbage collection by building with an empty `USE_GC` setting:
make USE_GC=
Performance testing used to cause OOM killer on the `stepA_mal` process in my VM:
Performance test for c:
Running: ../c/stepA_mal ../tests/perf1.mal
"Elapsed time: 2 msecs"
Running: ../c/stepA_mal ../tests/perf2.mal
"Elapsed time: 2 msecs"
Running: ../c/stepA_mal ../tests/perf3.mal
Killed
Here are the relevant syslog lines:
[938589.062424] Out of memory: Kill process 3769 (stepA_mal) score 877 or sacrifice child
[938589.063582] Killed process 3769 (stepA_mal) total-vm:957152kB, …

c: Add Boehm garbage collector

---

docs/FAQ.md

Fix typo in FAQ

---

docs/TODO
python/mal_types.py
python/stepA_mal.py
python/tests/stepA_mal.mal

`py!*`: Fix to work on both Python 2 and 3.
`py*`: Python types are converted to Mal types where applicable.
Added tests for Python interop.

python: Fix interop (py*, py!*)

---

racket/step6_file.rkt
racket/step7_quote.rkt
racket/step8_macros.rkt
racket/step9_try.rkt
racket/stepA_mal.rkt

I started working on automatic test for `*ARGV*` (expect a PR soon) and while testing I found that Racket wasn't setting *ARGV* at all. Now fixed.

racket: Set *ARGV* correctly

---

cpp/Types.cpp
cpp/Types.h
erlang/src/core.erl

* C++: Use int64_t for MalInteger type so it can properly hold `(time-ms)` values
* Erlang: Fix (time-ms) to return milliseconds instead of seconds

cpp, erlang: time-ms fixes

---

lua/core.lua
lua/tests/stepA_mal.mal
process/guide.md

First commit adds `lua-eval` core function and tests. Note that in Lua both "lists" and "hashmaps" are tables, so if the evaluated function returned an empty table we always return an empty Mal list. If it's not empty, we decide whether the table is a "list" or "hashmap" according to the first key - if it's numeric it'll be a Mal list, otherwise a Mal hashmap.
Second commit adds description of the optional `quux-eval` core function to the guide.

Add Lua interop and describe interop in the guide

---

js/core.js
js/interop.js
js/stepA_mal.js
js/tests/stepA_mal.mal
mal.html

* `js*` renamed to `js-eval` and is no longer a special form (just a normal   function in core.js)
* `.` is no longer a special form (just a normal function in core.js)
* fixed object/method parsing of first argument to `.`
* added tests for `.`
* updated mal.html: "Mal at a glance" shows all Mal functions
Probably solves #152 .

js: Fix interop, update web REPL page

---

elisp/core.el
elisp/stepA_mal.el
elisp/tests/stepA_mal.mal

While I was at it, I made elisp-eval a core function (as opposed to a special form) and made that one interop test more readable.

Replace elisp* with elisp-eval

---

.travis.yml
Makefile
README.md
logo/Dockerfile
logo/Makefile
logo/core.lg
logo/env.lg
logo/examples/tree.mal
logo/printer.lg
logo/reader.lg
logo/readline.lg
logo/run
logo/step0_repl.lg
logo/step1_read_print.lg
logo/step2_eval.lg
logo/step3_env.lg
logo/step4_if_fn_do.lg
logo/step5_tco.lg
logo/step6_file.lg
logo/step7_quote.lg
logo/step8_macros.lg
logo/step9_try.lg
logo/stepA_mal.lg
logo/tests/stepA_mal.mal
logo/types.lg

Tested on UCBLogo 6.0 with some minor tweaks (for performance and adding a native `timems` function).  The tweaks are performed during Docker image creation (see Dockerfile).
Tests of step 5 are skipped because UCBLogo is too slow.
Interop is available via `(logo-eval "logo code to run")`.
The `logo/examples` directory contains a Mal example of drawing a tree using turtle graphics.
So far I haven't had the patience of waiting for the entire self-hosted Mal tests. My guess is that tests like `(or false nil false nil false nil true)` will time out...
I managed to perform some other tweeks to UCBLogo which improve it's performance by 10-20% but we need something drastic to make this reasonable. I looked into NetLogo but: (a) haven't found a simple way for interactive input/output ; (b) it …

Logo implementation

---

README.md
crystal/Makefile
crystal/core.cr
crystal/printer.cr
crystal/reader.cr
crystal/step2_eval.cr
crystal/step3_env.cr
crystal/types.cr

I fixed Crystal implementation for Crystal 0.18.4.
I found that a test case for `time_ms` failed because it requires 64bit integer.  So I changed underlying type of `int` to `Int64`.  Now it works.

Crystal 0.18.4

---

swift3/Sources/core.swift
swift3/Sources/env.swift
swift3/Sources/printer.swift
swift3/Sources/reader.swift
swift3/Sources/step0_repl/main.swift
swift3/Sources/step1_read_print/main.swift
swift3/Sources/step2_eval/main.swift
swift3/Sources/step3_env/main.swift
swift3/Sources/step4_if_fn_do/main.swift
swift3/Sources/step5_tco/main.swift
swift3/Sources/step6_file/main.swift
swift3/Sources/step7_quote/main.swift
swift3/Sources/step8_macros/main.swift
swift3/Sources/step9_try/main.swift
swift3/Sources/stepA_mal/main.swift
swift3/Sources/types.swift

Main changes:
* consistency of func arguments, while every argument has both an outer and an inner name,
but the first argument's outer was "unnamed" by default in swift<2. now all arguments are consistent
and requires the initial "_" to declare the outer "unnamed" for the first argument
* indexes are now simpler types, the Array.index function computes successor/predecessor
* many, many API changes, that result in shorter "verb" names of functions with named arguments
ex: Array.joinWithSeparator(String) -> Array.joined(separator: String)

Squashed commits, updated to latest swift3 (swift-3.0-PREVIEW-2)

---

ada/Makefile
ada/core.adb
ada/reader.ads
ada/step0_repl.adb
ada/step0_repl.gpr
ada/step1_read_print.adb
ada/step1_read_print.gpr
ada/step2_eval.adb
ada/step2_eval.gpr
ada/step3_env.adb
ada/step3_env.gpr
ada/step4_if_fn_do.adb
ada/step4_if_fn_do.gpr
ada/step5_tco.adb
ada/step5_tco.gpr
ada/step6_file.adb
ada/step6_file.gpr
ada/step7_quote.adb
ada/step7_quote.gpr
ada/step8_macros.adb
ada/step8_macros.gpr
ada/step9_try.adb
ada/step9_try.gpr
ada/stepA_mal.gpr
ada/stepa_mal.adb

Hi,
I recently received four PATCHes from Nicholas Boulenguez :
0001-Replace-all-GNAT-projects-with-D-gnatmake-option.patch - Removes project files and changes the Makefile to compensate.  Applied with some changes for stepA_mal.
0002-Delegate-obj-directory-creatinon-to-gnatmake-p-optio.patch - Doesn't work because of patch 0001!
0003-Delegate-Ada-dependency-handling-to-gnatmake-instead.patch - gnatmake works out its own dependencies so there's no need to repeat them in the Makefile.  Applied in spirit.
0004-Use-Get_Line-fonction-instead-of-insisting-on-a-maxi.patch - Removes explicit limit on string length.  Applied with some minor changes.
Both sets of tests pass.  I compared the stats before and after 0003.  They were the same.
Regards,
Chris

Ada patches sep16

---

README.md
vimscript/Dockerfile
vimscript/core.vim
vimscript/env.vim
vimscript/printer.vim
vimscript/readline.vim
vimscript/step2_eval.vim
vimscript/step3_env.vim
vimscript/step4_if_fn_do.vim
vimscript/step5_tco.vim
vimscript/step6_file.vim
vimscript/step7_quote.vim
vimscript/step8_macros.vim
vimscript/step9_try.vim
vimscript/stepA_mal.vim
vimscript/tests/stepA_mal.mal
vimscript/types.vim
vimscript/vimextras.c

Changes:
* Dockerfile now installs Vim 8.0 (from source)
* Use lambdas for most functions in `core.vim` (this removed a lot of boilerplate code!)
* Use map+lambdas instead of `for` loops in several places
* Get rid of useless functions like ObjValue and ObjType to somewhat improve performance
* Fix bug in `time-ms` returning negative numbers
Not sure if there's any other improvement (Vim 8.0 has jobs, channels and JSON support - but not sure how these can help mal).

Vimscript: Use Vim 8.0

---

fsharp/step2_eval.fs
fsharp/step3_env.fs
fsharp/step4_if_fn_do.fs
fsharp/step5_tco.fs
fsharp/step6_file.fs
fsharp/step7_quote.fs
fsharp/step8_macros.fs
fsharp/step9_try.fs
fsharp/stepA_mal.fs

So that the repl won't quit to the shell on errors.

fsharp: added some top level exception catching 

---

process/guide.md

Ran into some problems with the <language>/run file
not having the executable flag set.
Setting +x on the run file helps this.
The error-message the python runner throws is:
Traceback (most recent call last):
File "../runtest.py", line 227, in <module>
r = Runner(args.mal_cmd, no_pty=args.no_pty)
File "../runtest.py", line 105, in __init__
env=env)
File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
restore_signals, start_new_session)
File "/usr/lib/python3.6/subprocess.py", line 1326, in _execute_child
raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
make: *** [Makefile:310: test^mymal^step0] Error 1

Update README with hint on test permission failing

---

go/src/types/types.go

It seems a bit more idiomatic to me - even I am just a beginner in Go.
Also, make "test^go" seems marginally faster (0.56s instead of 0.57s on my system)

Go: Use type assertions where possible instead of reflection

---

process/guide.md

it didn't incude the parantheses

Fix guide's explanation of Regex

---

elisp/reader.el

Unlike what I've read on `emacs-devel`, the problem is *not* gone in Emacs 25.2.  Maybe it will if Emacs 25.3 happens, but I'm no longer betting on that.

Apply hack to Emacs 25 instead of Emacs 25.1

---

.gitignore
.travis.yml
Makefile
README.md
livescript/Dockerfile
livescript/Makefile
livescript/core.ls
livescript/env
livescript/env.ls
livescript/node_readline.js
livescript/package.json
livescript/printer.ls
livescript/reader.ls
livescript/run
livescript/step0_repl.ls
livescript/step1_read_print.ls
livescript/step2_eval.ls
livescript/step3_env.ls
livescript/step4_if_fn_do.ls
livescript/step5_tco.ls
livescript/step6_file.ls
livescript/step7_quote.ls
livescript/step8_macros.ls
livescript/step9_try.ls
livescript/stepA_mal.ls
livescript/utils.ls

I've recently followed the mal guide to build an implementation in Livescript. It was really much fun! Thanks for the great guide!
I noticed there is an open pull request for another Livescript implementation, but the last comments on that thread are from 2015. So I thought I'll give it a try.
What do you think about my Livescript implementation?

Livescript implementation

---

bash/core.sh

Fixed wrong `string?` value on keyword arguments in bash implementation
(2 soft test fails).
Before the fix:
```
TEST: (string? :abc) -> ['',false] -> SOFT FAIL (line 115):
Expected : '(string? :abc)\r\nfalse'
Got      : '(string? :abc)\r\ntrue'
TEST: (string? (keyword "abc")) -> ['',false] -> SOFT FAIL (line 117):
Expected : '(string? (keyword "abc"))\r\nfalse'
Got      : '(string? (keyword "abc"))\r\ntrue'
```
With the fix:
```
TEST: (string? :abc) -> ['',false] -> SUCCESS
TEST: (string? (keyword "abc")) -> ['',false] -> SUCCESS
```

bash: Fix `string?` result on keyword arguments

---

gst/step0_repl.st
gst/step1_read_print.st
gst/step2_eval.st
gst/step3_env.st
gst/step4_if_fn_do.st
gst/step5_tco.st
gst/step6_file.st
gst/step7_quote.st
gst/step8_macros.st
gst/step9_try.st
gst/stepA_mal.st

I mistakenly assumed that the way to retrieve the current context is by calling a documented static method.  Apparently `thisContext` is the missing sixth keyword in Smalltalk, so that's not needed.

Fix init warning

---

elm/Eval.elm
elm/Printer.elm
elm/step1_read_print.elm
elm/step2_eval.elm
elm/step3_env.elm

- Removed the (direct) import of Env in step1 and step2.
- Simplified use of Eval in the first 3 steps.
- Cleaned up some debugging code in Printer.

Elm: Removed usage of Env from step1 and step2

---

php/core.php
php/step9_try.php
php/stepA_mal.php
php/types.php

This PR renames the Error class to _Error, so that it doesn't interfere with PHP 7's own internal Error class. Mal is otherwise running just fine with PHP 7.0.

Fix for PHP 7 compatibility 

---

elixir/Dockerfile
elixir/lib/mal/core.ex
elixir/lib/mix/tasks/step0_repl.ex
elixir/lib/mix/tasks/step1_read_print.ex
elixir/lib/mix/tasks/step2_eval.ex
elixir/lib/mix/tasks/step3_env.ex
elixir/lib/mix/tasks/step4_if_fn_do.ex
elixir/lib/mix/tasks/step5_tco.ex
elixir/lib/mix/tasks/step6_file.ex
elixir/lib/mix/tasks/step7_quote.ex
elixir/lib/mix/tasks/step8_macros.ex
elixir/lib/mix/tasks/step9_try.ex
elixir/lib/mix/tasks/stepA_mal.ex
elixir/mix.exs

The v1.0 syntax was deprecated, and threw a lot of deprecation warnings.  I fixed the warnings, and bumped the Elixir version to v1.5.  I shouldn't have introduced any bugs, but there aren't any tests, so hard to know for sure.

Update Elixir syntax & version to work with v1.5.x

---

elisp/core.el
elisp/types.el

I've remembered there was still one TODO left.  Speaking of which, is it OK to do a shallow copy for `with-meta` or could that be problematic for the atom type?  If I understand correctly this is about ensuring that the meta flag is independent for objects, even if their other properties are structurally shared.

Elisp fixes

---

cpp/Core.cpp
cpp/Makefile

Re: #298 
Also comes with a bonus Makefile fix to make macOS builds not depend on the version of readline installed by homebrew

C++ implementations of fn?/macro?/number?

---

vhdl/core.vhdl

We used to return milliseconds since 2000 but that number is too large to fit in a signed 32-bit integer.  Instead we now return the number of milliseconds since last midnight UTC, which is between 0 and 86399999 (still fits in a 32-bit signed integer).
Also removed unused variables from `define_core_function`.

vhdl: Fix time-ms: Return milliseconds since last midnight UTC to fit in 32-bit integer

---

c/Makefile

On my system libffi includes are put into a versioned (read: non-standard) directory, so I've made the Makefile a bit smarter to detect them properly.

C: Make use of pkg-config for libffi flags

---

process/guide.md

Guide was missing the deferrable step of having
a reader macro for ^ (which is included in the
tests for step A) which caused some confusion
as to what it was.
It's included in the tests/step1_read_print.mal
but not mentioned in the docs.

Update guide with note on reader macro with-meta

---

tests/step7_quote.mal
tests/step9_try.mal

Split from PR #310, to avoid accidentally breaking other implementations.
(after reading comment in PR #240) 
These catch three errors in the NASM implementation which only appeared in self-hosting.

New tests for steps 7 and 9

---

README.md

The link to the Common Lisp readme in the project readme was not formatted correctly. This is a small PR that just fixes that.

Fix typo in Common Lisp section of Readme

---

.gitignore
php/Makefile
php/README.md
php/stepA_mal.php
php/webrunner.php

Hi @kanaka,
This change is to make it easier to re-use `php/mal` in other projects. It pulls the web runner code out into `webrunner.php` and includes it at build time instead of including that code directly in `stepA_mal.php`.
I made this change to help with [frock](https://github.com/chr15m/frock), which is an experimental tool to build single-artifact PHP scripts from `mal` code. It relies heavily on and is itself written in `mal`. I also cleaned up the documentation a little.

PHP: refactor web running mechanism.

---

php/README.md
php/interop.php
php/reader.php
php/stepA_mal.php
php/tests/stepA_mal.mal

Hi @kanaka,
This is a change to the way the PHP interop presents to the end user and to clean up the interface. Interop is now exposed via the `php/` prefix for reaching into the PHP "namespace" and is the same for referencing functions and variables.
Previously to make native function call you'd do: `(! str_replace "l" "x" "hello")` whereas this patch changes it to work like this: `(php/str_replace "l" "x" "hello")`.
Likewise for referencing PHP global vars you previously used `($ "_SERVER")` whereas with this patch you instead use `php/_SERVER`.
These changes make the interop more Clojure-like which has e.g. the `js/...` namespace for referencing JavaScript objects. An added benefit is that editors now know you mean `php/str_replace` as a function call and will highlight it …

Updated PHP native interop interface.

---

tests/step4_if_fn_do.mal

In step 4, by mistake I implemented the `not` function in my host language rather than in mal itself as the guide instructs. And I did it poorly. `(not nil)` was returning `false`, and I managed to make it all the way past stepA, not finding the error until the self-hosting tests.
This little test in step 4 should help others I hope!

Test that (not nil) returns true

---

php/interop.php

Common ones which can't be called otherwise.
Can now be reached via php/exit, php/print, php/require.
Fixes chr15m/frock#7

PHP: Wrap some native "language constructs".

---

objc/core.m
objc/types.m

There are 15 failing tests with the objc implementation in stepA. ( Tested in Mac OS. )
I've tried to modify it to pass the tests.

ojbc: fix conj, meta and with-meta

---

process/guide.md

According to [Cheatsheet](http://kanaka.github.io/mal/process/cheatsheet.html) step 1 and some of implementations like [Python](https://github.com/kanaka/mal/blob/master/python/reader.py#L21) or [Javascript](https://github.com/kanaka/mal/blob/master/js/reader.js#L17), this function name should be `tokenize` in guide.

Fixing function name in guide

---

nim/step5_tco.nim
nim/step6_file.nim
nim/step7_quote.nim
nim/step8_macros.nim
nim/step9_try.nim
nim/stepA_mal.nim
tests/step6_file.mal
tests/step7_quote.mal

The description in process/guide.md states:
> The closure calls the your `EVAL` function using the `ast` as the first argument and the REPL environment (closed over from outside) as the second argument.
Reading this, I would expect
```
(def! a 1)
let* (a 1) (eval 'a))
```
to answer 1.
The only failing implementation is nim, and it seems to use a local environment instead of repl_env when evaluating the (locally evaluated) first argument.
The suggested test is after
`;>>> optional=True
and should be visible as an optional test.
I have no opinion about this, but process/guide.md should be updated if repl_env is not required.

Check that the eval built-in uses Repl instead of a local environment.

---

nasm/step9_try.asm
nasm/stepA_mal.asm

(try* A) evaluates A without setting an error handler. 
Addresses issue #341

NASM: Add catchless try to step 9 and step A

---

process/guide.md

Thank you for mal.  I've been enjoying working my way through the process. I've reached step 4, but not yet implemented vectors. The manual tests of `fn*` in step 4, though, use vectors to specify the function parameters. This may be idiomatic mal, but it doesn't work if you've deferred implementing vectors. Thus, I think it would be better to use lists here, like the automated tests do.

guide.md: Don't use vectors in step 4 when they're still deferrable.

---

tests/step4_if_fn_do.mal

Hello again. This is another discovery stemming from my extreme laziness. I haven't implemented strings yet, but a bunch of non-deferrable tests at step 4 use strings. I propose fixing this by two means: where the test is of string functionality, I've marked it as deferrable. Where the strings are just constants to be returned or printed by the code, I've replaced them with integers.

Mark step 4 tests that use strings as deferrable.

---

core.mal

Replace many (= (count xs) 0) with (empty? x).
Stop definining 'not', 'or' and 'cond' in core.mal, they are defined
in the process steps.
In 'some', avoid computing the same result twice.
Remove the final nil evaluation.

Trivial simplifications in core.mal.

---

process/guide.md
tests/step7_quote.mal
tests/step9_try.mal

Hello.  Here are two more fixes for tests that used deferrable features, a fix for an erroneous heading in a test, and a slight improvement to the ordering of the process guide.
PS: My BBC BASIC port has passed step 9, so now I'm busy implementing all the things I deferred.

Another round of minor doc/test fixes

---

ps/core.ps

A fix for a bug exposed by #358.

ps: Fix result of (concat [1 2]), so it returns a list not a vector.

---

ocaml/core.ml

It turns out that OCaml is close enough to the ML I learned as an undergraduate that I can fix this bug exposed by #358 as well.

ocaml: Fix result of (concat [1 2]), so it returns a list not a vector.

---

ada.2/core.adb
ada.2/step4_if_fn_do.adb
ada.2/step5_tco.adb
ada.2/step6_file.adb
ada.2/step7_quote.adb
ada.2/step8_macros.adb
ada.2/step9_try.adb
ada.2/stepa_mal.adb
cpp/Core.cpp
cpp/step8_macros.cpp
cpp/step9_try.cpp
cpp/stepA_mal.cpp

This PR follows the discussion at #360.
In Ada.2, convert `do` from built-in function to special form.
In C++, convert `map` from native definition to built-in function.
Also in C++, merge native functions and macros, the distinction was artificial.

Cpp ada.2 conformance

---

awk/reader.awk
bash/reader.sh
perl/reader.pm
python/reader.py
ruby/reader.rb
tcl/reader.tcl

These are some initial fixes for the unterminated-string bugs tested for by #359.  The first three are simple regexp matchers using the string part of the `tokenize` regexp.

Some fixes for unterminated strings

---

process/guide.md
tests/stepA_mal.mal

As discussed in #373, there are several functions that, while marked as optional in step A, do actually need to be defined in order for self-hosting to work, but don't need to do anything useful. This PR documents this situation and adds a test for it.

Document the requirements for optional step A functions

---

tests/stepA_mal.mal

In the BBC BASIC implementation, the empty list, vector, and hash-map are distinguished values and detected by their address.  Adding metadata to them makes a copy, and then they don't work properly any more.
Let's see if anyone else made that mistake...

step A: Test that metadata doesn't break empty collections.

---

gnu-smalltalk/reader.st
go/src/reader/reader.go
js/reader.js
lua/reader.lua
objpascal/reader.pas
php/reader.php
powershell/reader.psm1
racket/reader.rkt
rust/reader.rs
ts/reader.ts

Another batch of fixes for #359. These are split into two commits reflecting two different kinds of change that I made. The first batch add a new regexp test to detect a valid string, while the second modify an existing regexp to make it only match valid strings.

Unterminated string fixes: gnu-smalltalk, go, js, lua, objpascal, php, powershell, racket, rust, ts

---

tests/step4_if_fn_do.mal

Detected while attempting to rewrite let* with fn*.

test recursive definitions in let*

---

ada/reader.adb

Thanks bjh21. I have been distracted by a less important issue (should
"\a" be read as "\a" or "a"?).

ada: fix the fix for unterminated strings

---

tests/step6_file.mal

I just introduced a bug in the BBC BASIC implementation meaning that `load-file` was broken on files over 255 bytes long, and it was only caught by the optional test of `time-ms` in step A.  This change brings forward the relevant part of that test so the failure can be detected earlier and more obviously, at the same time as the other tests of `load-file`.
I've marked the new test as deferrable because it's needed for self-hosting (most of `mal/*.mal` are over 255 bytes), but not otherwise critical.

step6: Test loading of a large (>255 byte) file earlier than before.

---

bbc-basic/README.md
bbc-basic/core
bbc-basic/printer
bbc-basic/types

When I first submitted the BBC BASIC V implementation, it had some fairly grotty code for handling strings over 255 characters long because I'd written that code in a hurry and a grumpy mood. I've now re-written it and also made a few other clean-ups.
I've checked that the self-hosting tests still work.

bbc-basic: Assorted fixes

---

bbc-basic/run
bbc-basic/types

Self-hosting the performance tests turned out to defeat even my careful hand-tweaking of the balance between mal's heap and BASIC's string storage, so I've resorted to the crude approach of simply doubling Brandy's RAM allocation to a whole megabyte. That seems a bit extravagant, but it's Brandy's fault for having such a huge overhead for string arrays.

bbc-basic: Increase Brandy heap size so we run out of memory less

---

mal/env.mal

Heretofore, the mal implementation has linked each environment to its outer environment by defining a special symbol, `--outer--` in that environment.  This causes that symbol to be unusable by programs running under that implementation.  For instance:
```mal
(def! foo 123)
(def! f (fn* (--outer--) foo))
(f)
```
gives an error because overwriting `--outer--` breaks the environment chain.
Happily, mal provides a way around this.  Keywords are guaranteed to work as hashmap keys, so by using a keyword instead of a string as the key for the outer environment, it can be hidden from user code.  This also provides a motivation for keywords, which aren't otherwise used by the mal implementation.

mal: Use a keyword to link each environment to its outer one.

---

runtest.py

```
$ uname -a
CYGWIN_NT-10.0 wos-ThinkPad 2.11.2(0.329/5/3) 2018-11-08 14:34 x86_64 Cygwin
```
Tested (passed all tests): `awk`, `bash`, `make`, `perl`, `python`, `powershell`
https://github.com/kanaka/mal/issues/51#issuecomment-498034516

run test on cygwin

---

c/reader.c
d/reader.d

Here are a couple more fixes for #359. Nothing very interesting, though the D implementation of `read_atom` might benefit from some tidying by someone who knows the language.

Unterminated string fixes: c, d

---

tests/step1_read_print.mal

These tests are intended to catch the cases where the routine for reading a list, vector, or hashmap fails to consume the trailing token (`)`, `]`, or `}` as the case may be) from the input.  None of the existing step 1 tests detected this, and I only found it by playing around in the REPL.

step 1: Test reading some simple nested collections.

---

basic/reader.in.bas

One small step for #359.
I've essentially translated the BBC BASIC `FNunquote_string` into these more primitive dialects, including writing an implementation of `INSTR` in CBM BASIC because it's not natively present. Having discovered the lack of `INSTR` in CBM BASIC I considered rewriting the code to copy one character at a time into `R$`, but I decided that was likely to be much slower, so I stuck with the ersatz `INSTR`.

Unterminated string fix: basic

---

tests/step4_if_fn_do.mal

Certain naïve implementations of `=` (like the one I just wrote) will get this wrong, and no existing test at step 4 will catch it.

step 4: Test that (= (list nil) (list)) returns false.

---

vala/step2_eval.vala
vala/step3_env.vala
vala/step4_if_fn_do.vala
vala/step5_tco.vala
vala/step6_file.vala
vala/step7_quote.vala
vala/step8_macros.vala
vala/step9_try.vala
vala/stepA_mal.vala

The clause in eval_ast() which evaluates each element of an input
vector into an output vector was holding the intermediate results in
an ordinary GLib.List, and putting them all into a vector at the end
of the evaluation. But that meant that nothing was preventing all
those values from being garbage-collected half way through.
Now we make an output Mal.Vector at the start of the process, and
point a GC.Root at it to ensure it stays around until we've finished
putting items in it.
This fixes the vala part of #418, I think.

vala: avoid half-constructed vectors being garbage-collected.

---

nasm/types.asm

The `slurp` function can produce strings which end with an empty Array, if the input file is a multiple of the Array size. When appending such a string, `string_append_string` would keep reading past the end of the string, and continue until it ran out of memory. This fix adds a check for empty Array.
Partly fixes issue #418

NASM: Fix bug in str when appending empty arrays

---

tests/step4_if_fn_do.mal

These extra optional step4 tests would have caught the io implementation equality bug solved in #425 (specifically solved in commit 8e4de1ed14edf0c980643852d0663afa214e1202 ).
Note that this might reveal other implementations issues, but we won't see it clearly as Travis failures because these are part of the optional tests of step4 (should be hard failures from step9 onwards, IMO).

tests: step4: Add optional list and vector equality tests

---

io/MalTypes.io
tests/step1_read_print.mal

Instead of using Io's `asJson` method which escapes forward slashes, implement our own string escaping code so it fits the Mal requirements (escape only double-quotes, newline, and backslash).
The relevant step1 test was modified from soft to hard.

io: Fix unneeded escaping of forward slash

---

nasm/step5_tco.asm
nasm/step6_file.asm
nasm/step7_quote.asm
nasm/step8_macros.asm
nasm/step9_try.asm
nasm/stepA_mal.asm

Releasing function object prematurely led to segfaults after step 4 when evaluating:
```
((fn* () 4))
```
Now works on steps 5 to A.
Fixes issue #429

Fix nasm zero argument function call

---

tests/step8_macros.mal

This allows to test rewriting quasiquote as a macro, and should
change nothing else in theory.

test macroexpand without assuming that quasiquote is a special form

---

perl/core.pm
perl/interop.pm
perl/printer.pm
perl/reader.pm
perl/step2_eval.pl
perl/step3_env.pl
perl/step4_if_fn_do.pl
perl/step5_tco.pl
perl/step6_file.pl
perl/step7_quote.pl
perl/step8_macros.pl
perl/step9_try.pl
perl/stepA_mal.pl
perl/types.pm

The whole reason why I was looking at the Perl implementation was that I wondered whether it used `goto &name`. Here I finally get around to making it do so.
The first major change here is to replace the metadata implementation, symbolised by 28bff72. This uses a `Hash::Util::fieldhash` to hold all the metadata in a hash indexed by object ID, with automatic deletion when objects are garbage-collected. Along with this, most of the composite types lose a layer of indirection (771045a, d64a552, 329c9c2). This has a couple of down-sides:
* Turning a function into a macro causes it to lose its metadata
* Attaching metadata to a sequence or hash-map causes the whole array or hash to be copied, which might be expensive.
On the other hand, this removes a hash lookup from every access to a list, …

perl: New metadata and TCO and other changes

---

README.md
perl/README.md
perl/core.pm
perl/interop.pm
perl/printer.pm
perl/step3_env.pl
perl/step4_if_fn_do.pl
perl/step5_tco.pl
perl/step6_file.pl
perl/step7_quote.pl
perl/step8_macros.pl
perl/step9_try.pl
perl/stepA_mal.pl
perl/types.pm

I think I've reached the point where the changes I'm making to the perl implementation aren't actually making it any better, so here are the lest few that I think are actually good. I found a nicer way to implement keywords, eliminated the numbered variables in the special form switch, and documented things a little.

Final (?) perl improvements

---

tests/step4_if_fn_do.mal

Certain implementations like the one I wrote can get this wrong.

step 4: Test (if nil 1) returns nil

---

bbc-basic/reader.bas

This is a fix for #443 in BBC BASIC.

bbc-basic: Permit bare newlines in strings.

---

.travis.yml
Makefile
README.md
pike/Core.pmod
pike/Dockerfile
pike/Env.pmod
pike/Interop.pmod
pike/Makefile
pike/Printer.pmod
pike/Reader.pmod
pike/Readline.pmod
pike/Types.pmod
pike/run
pike/step0_repl.pike
pike/step1_read_print.pike
pike/step2_eval.pike
pike/step3_env.pike
pike/step4_if_fn_do.pike
pike/step5_tco.pike
pike/step6_file.pike
pike/step7_quote.pike
pike/step8_macros.pike
pike/step9_try.pike
pike/stepA_mal.pike
pike/tests/step5_tco.mal
pike/tests/stepA_mal.mal

Add a Mal implementation in Pike.
According to [its website](https://pike.lysator.liu.se/),
> Pike is a dynamic programming language with a syntax similar to Java and C. It is simple to learn, does not require long compilation passes and has powerful built-in data types allowing simple and really fast data manipulation.
The Dockerfile uses Pike v8.0 from Ubuntu bionic apt repo (8.0.498); I also tested locally with latest (8.0.702) compiled from source.
The implemenation passes all the tests and self-hosting tests. It also supports basic Pike interop with `pike-eval` (see `pike/tests/stepA_mal.mal`).
Performance:
```
$ make perf^pike
----------------------------------------------
Performance test for pike:
Running: env STEP=stepA_mal MAL_IMPL=js ../pike/run ../tests/perf1.mal
Elapsed time: …
```

Pike implementation

---

process/guide.md

This commit rewords the description of how to change the
apply/invoke case of EVAL for Step 5 (TCO). The new description
is clearer about how to set the exrps argument of the new
environment being created.

Clarify Step 5 of the implementation guide

---

.travis_test.sh

Bash 5 doesn't like periods in variable names so this commit performs a substitution to double underscores to avoid them. Fixes #456.

Fix Travis test script to work with Bash 5

---

python.2/env.py
python.2/mal_types.py
python.2/run

Performance is improved about 77% on my system
Optimizations:
* remove use of `ABC`/`abstractmethod`
* start new environments with copy of `outer`; no need to `find(key)`
* run with asserts off

Improve python.2 performance on perf3 benchmark by 77%

---

README.md

I missed the authors table when originally submitting the `python.2` implementation.

Add missing python.2 author (myself) to README.md

---

tests/step8_macros.mal

I had a bug in the Wren implementation of `nth` that slipped all the way to self-hosting.
Adding these tests caught it early in step8 when we introduce `nth`.

tests: step8: Verify nth doesn't throw on nil elements

---

.travis.yml
Makefile
README.md
wren/Dockerfile
wren/Makefile
wren/README.md
wren/core.wren
wren/env.wren
wren/interop.wren
wren/printer.wren
wren/reader.wren
wren/readline.wren
wren/run
wren/step0_repl.wren
wren/step1_read_print.wren
wren/step2_eval.wren
wren/step3_env.wren
wren/step4_if_fn_do.wren
wren/step5_tco.wren
wren/step6_file.wren
wren/step7_quote.wren
wren/step8_macros.wren
wren/step9_try.wren
wren/stepA_mal.wren
wren/tests/step5_tco.mal
wren/tests/stepA_mal.mal
wren/types.wren
wren/wren-add-gettimeofday.patch

A new Mal implementation in [Wren](http://wren.io/), tested with Wren 0.2.0. It includes Mal-Wren interop via the `wren-eval` function; see `tests/stepA_mal.mal` for examples.
The implementation passes all tests and self-hosting tests. On my machine it's faster than python3 and slower than Ruby 2.5.
Wren doesn't have a regexp module, so I ended up tokenizing the input string char-by-char. I found no easy way to add Wren modules with native code at runtime (it's pretty easy to add modules when you compile the whole Wren interpreter).
For `time-ms` I found no workaround and ended-up adding a C call to the system's `gettimeofday` function. The modification to the interpreter is in `wren/wren-add-gettimeofday.patch` (the `Dockerfile` applies this patch before building the interpreter). I'll …

Wren implementation

---

bash/stepA_mal.sh
bash/tests/stepA_mal.mal

This supercedes kanaka#470 and includes kanaka#471.
This fixes some edge cases when passing an asterisk to an sh* interop call.
Before this fix mal would pass the string with any wildcard character converted to __STAR__ when passing to the subcommand.
For example `(sh* "ls *")` would become `ls __STAR__` when executed.
See the tests for examples of where this would fail to do what the user expects.
See also: chr15m/flk#1

Fix bash interop asterisk quoting

---

bash/stepA_mal.sh
bash/tests/stepA_mal.mal

Before this fix the 'sh*' function was joining the lines of the output of whatever command was run in a way that resulted in '\n' instead of a literal carriage return.
Without this fix:
```
$ ./mal
Mal [bash]
user> (println (sh* "head mal"))
#!/usr/bin/env bash\n#\n# mal (Make a Lisp) object types\n#\n\nif [ -z "${__mal_types_included__}" ]; then\n__mal_types_included=true\n\ndeclare -A ANON\n
nil
```
After this fix (carriage returns correctly inserted by `sh*`):
```
$ ./mal
Mal [bash]
user> (println (sh* "head mal"))
#!/usr/bin/env bash
#
#
if [ -z "${__mal_types_included__}" ]; then
__mal_types_included=true
declare -A ANON
nil
```

Fix Bash implementation interop carriage returns.

---

python.2/env.py
tests/step6_file.mal

It should search the outer Env
Currently unit tests fail:
```
$ python -m unittest discover -s tests
.....F...............................4
..........................................................."exc is:" "'abc' not found"
.............
======================================================================
FAIL: test_env_find_outer (test_step3.TestStep3)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/aw/Projects/cureatr/dev/cureatr/experiments/lispy/mal/python.2/tests/test_step3.py", line 23, in test_env_find_outer
self.assertTrue(result is outer)
AssertionError: False is not true
----------------------------------------------------------------------
Ran 109 tests in 0.545s
FAILED (failures=1)
```

Fix python.2 Env.find implementation.

---

swift5/.gitignore
swift5/Makefile
swift5/run

Get rid of swift dependency to run tests as discussed in #467

swift5: get rid of swift dependency to run tests

---

es6/step8_macros.mjs
es6/step9_try.mjs
es6/stepA_mal.mjs
js/step8_macros.js
js/step9_try.js
js/stepA_mal.js
python/step8_macros.py
python/step9_try.py
python/stepA_mal.py
ruby/step8_macros.rb
ruby/step9_try.rb
ruby/stepA_mal.rb

Modify `defmacro!` to clone the given function before setting the `ismacro` flag.
This fixes a soft-fail test in stepA.
(there are other implementations which still don't support it.)

es6, js, python, ruby: defmacro! doesn't mutate original function

---

impls/tests/step6_file.mal

All of the existing `read-string` tests test forms whose end can be detected before the end of the input string, either because they're naturally self-terminating (lists, strings) or because there's white space after them.  All of the uses of the reader from the REPL are similarly likely to have input with a newline or similar at the end.
My BCPL implementation turned out to read one character past the end of the input when the input ended inside an atom, and to incorporate that one byte into the output.  The consequences of a buffer over-read are a little unpredictable, so I've just written a test that was good enough to catch the bug for me.

Step 6: Test read-string of a single atom at the end of input

---

impls/tests/step9_try.mal

In BCPL, my `throw` implementation uses `longjump()`, which is similar to C's `longjmp()`.  I have a pair of global variables that specify the current exception handler, and `try*` updates them on entry. While making sure that `try*` also restored the exception handler on exit, I noticed that no current tests in step 9 covers this case: they don't try using `throw` after `try*` has returned, or from inside a `catch*` block.  So here are a couple of tests that do.

Add tests for nested exception handlers

---

README.md
impls/.gitignore
impls/lua/Dockerfile
impls/lua/Makefile
impls/lua/core.lua
impls/lua/printer.lua
impls/lua/reader.lua
impls/lua/types.lua

I tried the lua implementation with lua 5.3.5 and found a various issues.
- Readme said it was tested with 5.2 but the makefile is looking for the libraries in a 5.1 directory. I updated the makefile to be version agnostic. I also added a step to install rex_pcre.so through luarocks.
- It seems it also needs LuaSocket. To make it easier I just commented the require and changed `ms-time` to use `os.clock` (won't give time in ms).
- `loadstring` is now `load` in newer versions of lua.
- Lua now supports unicode, so I changed `\177` to `\u{029e}` to be more like some of the other implementations.
- Some tests were failing, reason was that the `keyword` implementation was wrong.
- There is still one test soft failing that I haven't looked at in detail yet (I don't think it's lua version …

Update and fixes for the lua implementation.

---

runtest.py

This is a successor to #469. There, I found that my BCPL implementation (now almost finished!) was tripping up `runtest.py` by omitting carriage returns in its output where they would have no effect. This appears to be a feature of the BCPL standard library and hard to avoid.  More recently, I've started on an APL implementation and found that GNU APL's readline-alike is very enthusiastic about emitting escape sequences.
This PR modifies `runtest.py` so that it's more tolerant of this kind of behaviour without the extravagant overhead of building an entire terminal emulator into it.
The important feature is that I've stopped `runtest.py` caring about how its input is echoed.  Previously when testing a form, it would check not only that the form was evaluated correctly, but also that it …

Simplify runtest.py's input handling

---

impls/tests/step2_eval.mal
impls/yorick/step2_eval.i
impls/yorick/step3_env.i

An empty vector or hash-map should evaluate to itself, but I reached the test of `(empty? [])` in step 4 before I discovered that I'd got `[]` evaluating to `0`.  Add tests for both cases to step 2.  This shouldn't cause any new failures, unless I suppose there's an implementation where `(empty? 0)` is true. It just means that this bug in `eval_ast` can be caught before it propagates to two more stage files.

Step 2: Test empty vectors and hash-maps

---

runtest.py

If a test times out, that means the implementation hasn't returned a prompt within reasonable time.  Continuing to type at it is unlikely to be helpful, since the lack of a prompt indicates that the subprocess has hung, so subsequent tests are likely to time out as well.
This is particularly annoying in step 5, where the line that usually times out, `(def! res2 (sum2 10000 0))` has its output ignored, so a timeout is treated as success, meaning that runtest proceeds to the next test, which of course also times out.
This PR converts timeouts into fatal errors (through the existing exception-handing mechanism) so that a timeout immediately aborts the entire test.

runtest: Treat test timeouts as fatal

---

impls/bash/core.sh
impls/bash/env.sh
impls/bash/reader.sh

OSH is a bash-compatible shell: https://www.oilshell.org/
reader.sh:
- Put the constant regex pattern in a string literal.  This simplifies
it by removing mixed regex vs. shell quoting, and implicit
concatenation with $'\n'.
This is suggested by the bash manual:
https://www.gnu.org/software/bash/manual/bash.html#Conditional-Constructs
"Storing the regular expression in a shell variable is often a useful
way to avoid problems with quoting characters that are special to the
shell."
- Initialize __reader_tokens as an array, not a string.
https://www.oilshell.org/release/0.8.pre6/doc/known-differences.html#values-are-tagged-with-types-not-cells
env.sh:
Simplify quoting in 'eval' expressions.  This quotes associative array keys,
which is required by OSH to avoid dynamic parsing. …

impls/bash: Minor changes to make it run under OSH

---

impls/ruby/core.rb

Before the fix Ruby had one soft fail in step9:
```
TEST: '(keyword :abc)' -> ['',:abc] -> SOFT FAIL (line 386):
Expected : '.*\n\\:abc'
Got      : '(keyword :abc)\n:\xca\x9eabc'
```
The fix causes `(keyword :abc)` to return its keyword argument without modification.

ruby: (keyword :abc) should just return same keyword

---

impls/tcl/core.tcl
impls/tcl/step8_macros.tcl
impls/tcl/step9_try.tcl
impls/tcl/stepA_mal.tcl
impls/tcl/types.tcl

Fixes of soft test failures in step 9 and step A:
- tcl: Fix (keyword) of keywords
- tcl: defmacro! doesn't modify existing functions

tcl: Soft failure fixes

---

impls/ts/core.ts
impls/ts/package.json
impls/ts/step8_macros.ts
impls/ts/step9_try.ts
impls/ts/stepA_mal.ts
impls/ts/types.ts

TypeScript travis jobs have been failing for a while:
https://travis-ci.org/github/kanaka/mal/jobs/732329501
```
./node_modules/.bin/tsc -p ./
node_modules/@types/node/index.d.ts:20:1 - error TS1084: Invalid 'reference' directive syntax.
20 /// <reference lib="es2016" />
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:11: recipe for target 'step0_repl.js' failed
```
I upgraded the TypeScript version in package.json (required a minor fix in
core.ts) to solve the issue, and took the chance to fix a couple of soft test
failures.

typescript: Upgrade to 4.0.3 + soft-failure fixes

---

process/guide.md

I was following your (awesome) tutorial when I found a typo, so I fixed it :)

Fix typo in guide.md

---

process/guide.md

This change removes one level of indentation on the note about using `throw` (which is not yet defined) when defining the `cond` macro at the end of Step 8. The Markdown engine on Github cannot start an indented list following a block of code, so it treats the bullet as 4-space indented code, causing the bullet point to be formatted as ugly pre-formatted text.

Fix formatting of note about `throw` when defining `cond` (Step 8)

---

docs/FAQ.md

The FAQ seems to reference some nonexistent (older?) script.
Updated to what is specified in `.travis.yml`.

Update CI info in FAQ

---

process/guide.md

As is this was confusing, but from tests it's clear that all the types should support meta/with-meta.

Fix with-meta and meta description in guide

---

impls/fantom/Dockerfile
impls/fantom/src/mallib/fan/core.fan
impls/fantom/src/mallib/fan/interop.fan
impls/fantom/src/mallib/fan/types.fan
impls/fantom/src/step2_eval/fan/main.fan
impls/fantom/src/step3_env/fan/main.fan
impls/fantom/src/step4_if_fn_do/fan/main.fan
impls/fantom/src/step5_tco/fan/main.fan
impls/fantom/src/step6_file/fan/main.fan
impls/fantom/src/step7_quote/fan/main.fan
impls/fantom/src/step8_macros/fan/main.fan
impls/fantom/src/step9_try/fan/main.fan
impls/fantom/src/stepA_mal/fan/main.fan
impls/fantom/tests/stepA_mal.mal
impls/tests/step1_read_print.mal

* Fix #513 in Fantom and similar problems with Fantom's interop (all related to empty lists and hash-maps)
* Fix broken step1 (and step6) test involving a `!` char - requires rebuilding the Docker image because I've added a java config option to disable jLine's expand events. I've also moved that test to be mandatory in step1 (because the comment said that fantom is the only offender)
* Fix step9 optional test - `(keyword :abc)`
* Fix stepA optional test - defmacro! doesn't mutate the original function

Fantom fixes

---

impls/tests/step4_if_fn_do.mal

Another  test of empty things, because those are special in APL.  Since #512 smoked out a bug elsewhere, I think this one is worth trying.
In APL, empty arrays have type, and the `≡` function pays attention to that, so if you're not careful empty lists produced by different means compare different.  This test detects that by comparing an empty list produced by `list` with one produced by evaluating an empty list.
My bug was found by a deferrable step 4 test, but the bug should be non-deferrable.

step 4: Test that (= (list) ()) is true

---

impls/tests/step7_quote.mal
impls/tests/step9_try.mal

In #513, @dubek noted two additional ways to make empty lists in fantom that compare different from an empty list made by evaluating an empty list.  This adds tests for those, along with another two that might fail similarly (but don't in fantom).

Test equality of other kinds of empty list

---

process/guide.md

See #536. Another thing I'm less sure about: Do the paths mentioning tests/ and process/ need to be adjusted, too?

Mention impls/quux instead of quux when needed

---

impls/tests/step1_read_print.mal

Heya - I might be wrong, but I think this line needs to be added - it's the expected output from evaluating the line above - `1; &()*+,-./:;<=>?@[]^_{|}~`

Add missing expected result for test case

---

IMPLS.yml
README.md
impls/janet/Dockerfile
impls/janet/core.janet
impls/janet/env.janet
impls/janet/printer.janet
impls/janet/reader.janet
impls/janet/run
impls/janet/step0_repl.janet
impls/janet/step1_read_print.janet
impls/janet/step2_eval.janet
impls/janet/step3_env.janet
impls/janet/step4_if_fn_do.janet
impls/janet/step5_tco.janet
impls/janet/step6_file.janet
impls/janet/step7_quote.janet
impls/janet/step8_macros.janet
impls/janet/step9_try.janet
impls/janet/stepA_mal.janet
impls/janet/tests/stepA_mal.mal
impls/janet/types.janet
impls/janet/utils.janet

This is an implementation of mal in [janet](https://janet-lang.org).
All tests pass in both direct and self-hosted modes:
```
make "test^janet"
make MAL_IMPL=janet "test^mal"
```
One notable feature is the use of peg parsing instead of regular expressions as Janet has built-in support for the former but not the latter.
Included in the PR is a Dockerfile I successfully tested in a VM.

Add Janet implementation

---

IMPLS.yml
Makefile.impls
impls/fennel/Dockerfile
impls/fennel/Makefile
impls/fennel/core.fnl
impls/fennel/env.fnl
impls/fennel/printer.fnl
impls/fennel/reader.fnl
impls/fennel/run
impls/fennel/step0_repl.fnl
impls/fennel/step1_read_print.fnl
impls/fennel/step2_eval.fnl
impls/fennel/step3_env.fnl
impls/fennel/step4_if_fn_do.fnl
impls/fennel/step5_tco.fnl
impls/fennel/step6_file.fnl
impls/fennel/step7_quote.fnl
impls/fennel/step8_macros.fnl
impls/fennel/step9_try.fnl
impls/fennel/stepA_mal.fnl
impls/fennel/types.fnl
impls/fennel/utils.fnl

This is an implementation of mal in [Fennel](https://fennel-lang.org/).
All tests pass in both direct and self-hosted modes:
make "test^fennel"
make MAL_IMPL=fennel "test^mal"
I also used a peg in this implementation and not regular expressions.
Included in the PR is a Dockerfile I successfully tested in a VM.
I haven't changed the README yet -- thought I might wait to see what happens with the Janet PR.

Add Fennel implementation

---

process/guide.md

Guide: formaly introduce map and vector literals

---

process/guide.md

The sample Makefile snippets are accurate; the file reference just says `Makefile` when it should be `Makefile.impls`.

Fix reference to Makefile.impls in guide.

---

impls/haskell/Core.hs
impls/haskell/Env.hs
impls/haskell/Printer.hs
impls/haskell/Reader.hs
impls/haskell/Types.hs
impls/haskell/step1_read_print.hs
impls/haskell/step2_eval.hs
impls/haskell/step3_env.hs
impls/haskell/step4_if_fn_do.hs
impls/haskell/step5_tco.hs
impls/haskell/step6_file.hs
impls/haskell/step7_quote.hs
impls/haskell/step8_macros.hs
impls/haskell/step9_try.hs
impls/haskell/stepA_mal.hs
impls/tests/step3_env.mal
impls/tests/step4_if_fn_do.mal

The grammar is not fully equivalent to the one in the process, but it
passes all tests.
I suggest that it becomes a formal/testable reference (are tabs
allowed as spaces? is "a~" valid? is "' a" valid?...).
As it is formuled here, it can directly be translated either to
another language with high-level parsers, or to a low-level language
as each production only switches after a look at the next input
character.

haskell: clarify reader

---

impls/mal/step0_repl.mal
impls/mal/step2_eval.mal
impls/mal/step3_env.mal
impls/mal/step4_if_fn_do.mal
impls/mal/step6_file.mal
impls/mal/step7_quote.mal
impls/mal/step8_macros.mal
impls/mal/step9_try.mal
impls/mal/stepA_mal.mal

An uncaught exception in the self-hosting implementation causes the
interpreter to display the EVALed ast for each EVAL level until the
exception, something similare to a stack trace.  This does not cost
much and may help a lot debugging the self-hosting step.
On the other hand, remove try* from step0 where it serves no useful
purpose.
Because of indentation level, this diff is better viewed with the git
-b command line option.

Print a stack trace for uncaught exceptions in self-hosting

---

impls/java-truffle/README.md
impls/java-truffle/build.gradle
impls/java-truffle/make-native.sh
impls/java-truffle/src/main/java/truffle/mal/Core.java
impls/java-truffle/src/main/java/truffle/mal/MalEnv.java
impls/java-truffle/src/main/java/truffle/mal/Types.java
impls/java-truffle/src/main/java/truffle/mal/step2_eval.java
impls/java-truffle/src/main/java/truffle/mal/stepE_macros.java

This PR addresses #568, fixing issues that prevented the compilation of GraalVM native images
for the java-truffle Mal implementation.
In addition, a `make-native.sh` convenience script has been provided for those who wish to try building native images themselves. I have not changed the Makefile or run script to use native images, as each step takes almost a minute to build on my machine. There may also be some stability issues with the AOT compilation process; out ~40 compilation attempts, I had 2 SIGSEGV crashes that were not repeatable.

Java truffle native image

---

impls/tests/step9_try.mal

This was a bug that took me a while to find in the self-hosting step. In my case, it had to do with javascript's object copying system.

additional test

---

impls/ada.2/core.adb
impls/ada.2/types-atoms.adb
impls/ada.2/types-atoms.ads

ada.2: stop supporting metadata for atoms

---

README.md
impls/scheme/Dockerfile
impls/scheme/Makefile

CHICKEN has had a new major version for a while now. I've taken the chance to do the following changes:
- Bump the Docker image to Ubuntu Focal (the latest stable version with C5)
- Adapt the Makefile to C5
- Update all other Scheme installations
- Update the README
What's left is for @kanaka to trigger a Docker image rebuild and see whether it works on Travis.

Update Scheme implementations

---

impls/ruby.2/core.rb

Hello.
The current version crashes for `(rest (list 6))`.

ruby.2: fix (rest (list 6))

---

impls/python/reader.py

the error was because it is not converted to float change the line 34
from
elif re.match(float_re, token): return **_int_**(token)
to 
elif re.match(float_re, token): return **_float_**(token)

solve issue Floats don't work in the python implementation. #646

---

.gitignore
impls/.gitignore

Hello and thanks for the great work on MAL! I've just started working through it and am really enjoying it so far. Something I found odd however is that `package-lock.json` appears in a few `.gitignore` files. Was this intentional?
AFAIK `package-lock.json` file is intended to be checked in to source control in order to make builds reproducible; without a `package-lock.json` file `npm install` becomes non-deterministic.
See e.g. https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json:
> package-lock.json is automatically generated for any operations where
> npm modifies either the node_modules tree, or package.json. It describes
> the exact tree that was generated, such that subsequent installs are
> able to generate identical trees, regardless of intermediate dependency
> …

Suggestion: Remove package-lock.json from .gitignore files

---

impls/js/reader.js

parseFloat does not take a base parameter

Javascript: fix reader, remove base argument to parseFloat

---

impls/ada.2/core.adb
impls/erlang/src/core.erl
impls/erlang/src/printer.erl
impls/erlang/src/step8_macros.erl
impls/erlang/src/step9_try.erl
impls/erlang/src/stepA_mal.erl
impls/fsharp/core.fs
impls/haskell/Core.hs
impls/mal/core.mal
impls/mal/env.mal
impls/mal/step2_eval.mal
impls/mal/step3_env.mal
impls/mal/step4_if_fn_do.mal
impls/mal/step6_file.mal
impls/mal/step7_quote.mal
impls/mal/step8_macros.mal
impls/mal/step9_try.mal
impls/mal/stepA_mal.mal
impls/nasm/core.asm
impls/prolog/core.pl
impls/sml/core.sml
impls/tests/step9_try.mal
impls/vimscript/core.vim
process/guide.md

Hello.
This merge request contains 3 commits implementing three ideas, and a backport from #592.  The suggestions are interconnected, so a single merge request is convenient for now to start discussion and list implementations for which `apply` refuses macros.

mal: error reporting, procedural env_set, native macro?

---

impls/make/README
impls/make/core.mk
impls/make/env.mk
impls/make/gmsl.mk
impls/make/numbers.mk
impls/make/printer.mk
impls/make/reader.mk
impls/make/readline.mk
impls/make/step0_repl.mk
impls/make/step1_read_print.mk
impls/make/step2_eval.mk
impls/make/step3_env.mk
impls/make/step4_if_fn_do.mk
impls/make/step6_file.mk
impls/make/step7_quote.mk
impls/make/step8_macros.mk
impls/make/step9_try.mk
impls/make/stepA_mal.mk
impls/make/types.mk
impls/make/util.mk

Please find details are in the commit header.

Intrusive changes in the make implementation

---

impls/python/core.py
impls/python/env.py
impls/python/mal_readline.py
impls/python/mal_types.py
impls/python/printer.py
impls/python/reader.py
impls/python/step0_repl.py
impls/python/step1_read_print.py
impls/python/step2_eval.py
impls/python/step3_env.py
impls/python/step4_if_fn_do.py
impls/python/step5_tco.py
impls/python/step6_file.py
impls/python/step7_quote.py
impls/python/step8_macros.py
impls/python/step9_try.py
impls/python/stepA_mal.py

python_MODE=python3 crashes on impls/python/tests/step5_tco.mal, but
it also does on the current head.
Replace some lambda constructs with more idiomatic generator
expressions, removing several temporary sequences (conversions,
contatenations, slices, arguments).
Remove obsolete coll_Q test and preservation of metadata by conj.
Use normal classes for functions in order to simplify cloning and
membership tests.
Close file open by 'slurp' after reading.
Derive List and Vector from tuple, which is more efficient than list
for immutable structures.  Remove the need for __getitem__ stuff.
Search in outer environments with a loop instead of a recursion.
Replace most python2/3 wrappers with code compatible with both
versions.  Use a non-printable ASCII characters instead of Unicode
characters …

python: various simplifications

---

Makefile.impls
impls/wasm/Makefile
impls/wasm/step2_eval.wam
impls/wasm/step3_env.wam
impls/wasm/step4_if_fn_do.wam
impls/wasm/step5_tco.wam
impls/wasm/step6_file.wam
impls/wasm/step7_quote.wam
impls/wasm/step8_macros.wam
impls/wasm/step9_try.wam
impls/wasm/stepA_mal.wam

Also prevent macros from mutating functions and implement DEBUG-EVAL.

Wasm: merge EVAL_AST into EVAL

---

IMPLS.yml
Makefile.impls
README.md
impls/latex3/Dockerfile
impls/latex3/Makefile
impls/latex3/core.sty
impls/latex3/env.sty
impls/latex3/printer.sty
impls/latex3/reader.sty
impls/latex3/run
impls/latex3/step0_repl.tex
impls/latex3/step1_read_print.tex
impls/latex3/step2_eval.tex
impls/latex3/step3_env.tex
impls/latex3/step4_if_fn_do.tex
impls/latex3/step6_file.tex
impls/latex3/step7_quote.tex
impls/latex3/step8_macros.tex
impls/latex3/step9_try.tex
impls/latex3/stepA_mal.tex
impls/latex3/types.sty
impls/tests/step3_env.mal
impls/tests/step9_try.mal

It requires two cosmetic changes to existing tests.

New LaTeX3 implementation

---

impls/lib/pprint.mal

Current implementation of **pprint** is not compatible with implementations using languages that do not guarantee that **keys** on a _hash-map_ keep ordering (e.g. Go language).
This PR corrects this.

pprint properly prints hash-maps

---

IMPLS.yml
impls/vbs/run

By checking the [logs](https://github.com/kanaka/mal/issues/662#issuecomment-2305841001) provided by @kanaka , I realize that the problem is caused by the different path specifications in `win` and `linux`.
There was no problem before because normal tests used relative paths, while self-hosted tests used absolute paths.

Fix VBScript implementation self-hosting fails to start issue

---

README.md
impls/python.2/Dockerfile
impls/python.2/Makefile
impls/python.2/core.py
impls/python.2/env.py
impls/python.2/mal_readline.py
impls/python.2/mal_types.py
impls/python.2/reader.py
impls/python.2/run
impls/python.2/step0_repl.py
impls/python.2/step1_read_print.py
impls/python.2/step2_eval.py
impls/python.2/step3_env.py
impls/python.2/step4_if_fn_do.py
impls/python.2/step5_tco.py
impls/python.2/step6_file.py
impls/python.2/step7_quote.py
impls/python.2/step8_macros.py
impls/python.2/step9_try.py
impls/python.2/stepA_mal.py
impls/python.2/tests/step5_tco.mal
impls/python.2/tests/stepA_mal.mal
impls/tests/step4_if_fn_do.mal
impls/tests/step9_try.mal
impls/tests/stepA_mal.mal

I have almost rewritten the python.2 implementation, but in the same direction and based on the work by @epylar. I suggest to merge all the ideas he agrees with.
The most intrusive suggestion is the removal of an external parser library. The MAL grammar is so simple that a parser does not help much, and general libraries are difficult to type-check.
Also, the impls/python.2/tests/*.py are out of sync (and were before this suggestion).  Are they useful after the initial development?  If we update them, Makefile should run them.
By the way, python.2 belongs to the past now.  Should we not merge the two python
implementations?
Changelog:
Check the whole code with flake8, pylint and mypy.
Report all possible errors with extensive context.
Demonstrate iterators, decorators, functional tools, …

python.2: fix tests, use source checkers and more python3 features

---

impls/purs/src/step2_eval.purs
impls/purs/src/step3_env.purs
impls/purs/src/step4_if_fn_do.purs
impls/purs/src/step5_tco.purs
impls/purs/src/step6_file.purs
impls/purs/src/step7_quote.purs
impls/purs/src/step8_macros.purs
impls/purs/src/step9_try.purs
impls/purs/src/stepA_mal.purs

Hello.
These changes should be part of #592 , but
- the merge request adding the purescript implementation has been accepted before it,
- I had to update some settings for the latest purescript. @mrsekut, could you please review them ?.

Merge eval and evalAST in purescript implementation

---

impls/mal/step2_eval.mal
impls/mal/step3_env.mal
impls/mal/step4_if_fn_do.mal
impls/mal/step6_file.mal
impls/mal/step7_quote.mal
impls/mal/step8_macros.mal
impls/mal/step9_try.mal
impls/mal/stepA_mal.mal

This does not seem worth a test, but can currently break the self-hosting.

mal: implement DBGEVAL without assuming that a: is a valid symbol

---

impls/wasm/env.wam
impls/wasm/step3_env.wam
impls/wasm/step4_if_fn_do.wam
impls/wasm/step5_tco.wam
impls/wasm/step6_file.wam
impls/wasm/step7_quote.wam
impls/wasm/step8_macros.wam
impls/wasm/step9_try.wam
impls/wasm/stepA_mal.wam

A trivial simplification lost during the merge of eval ast.

wasm: remove the now unneeded ENV_FIND environment method

---

impls/wasm/core.wam

Added support for `seq` for the `wasm` implementation.
Pull request requirements:
the implementation name.
Additional requirements if you are adding a new implementation (see [FAQ](../docs/FAQ.md#add_implementation) for details):

wasm: add seq

---

impls/ada.2/Dockerfile
impls/ada.2/envs.ads
impls/ada.2/run
impls/ada.2/step5_tco.adb
impls/ada.2/step6_file.adb
impls/ada.2/step7_quote.adb
impls/ada.2/step8_macros.adb
impls/ada.2/step9_try.adb
impls/ada.2/stepa_mal.adb
impls/nim/Dockerfile
impls/nim/core.nim
impls/nim/env.nim
impls/nim/reader.nim
impls/nim/run
impls/nim/step0_repl.nim
impls/nim/step3_env.nim
impls/nim/step4_if_fn_do.nim
impls/nim/step5_tco.nim
impls/nim/step6_file.nim
impls/nim/step7_quote.nim
impls/nim/step8_macros.nim
impls/nim/step9_try.nim
impls/nim/stepA_mal.nim
impls/tests/step4_if_fn_do.mal

I have found this in an old mess of experimentations with ada.2.  Seems simple and worth testing.

New test for closures

---

impls/hy/step2_eval.hy
impls/hy/step3_env.hy
impls/hy/step4_if_fn_do.hy
impls/hy/step5_tco.hy
impls/hy/step6_file.hy
impls/hy/step7_quote.hy
impls/hy/step8_macros.hy
impls/hy/step9_try.hy
impls/hy/stepA_mal.hy

Original issue describing the change and converting the first set of implementations: https://github.com/kanaka/mal/pull/592
Tracking issue for other implementations: https://github.com/kanaka/mal/issues/657

hy: merge eval_ast/macroexpand into EVAL. Add DEBUG-EVAL.

---

impls/io/Dockerfile
impls/io/Makefile
impls/io/run

Build Io interpreter and packages from source in latest Ubuntu.
The interpreter looks for packages under `eerie` in the current directory, so create the symlink in the Makefile that is "building" each step.
Now the Regex package no longer prints a message when loaded, so no need for the special treatment in `run`.
----
Pull request requirements:
the implementation name.

io: Update Dockerfile

---

impls/rpython/env.py
impls/rpython/step2_eval.py
impls/rpython/step3_env.py
impls/rpython/step4_if_fn_do.py
impls/rpython/step5_tco.py
impls/rpython/step6_file.py
impls/rpython/step7_quote.py
impls/rpython/step8_macros.py
impls/rpython/step9_try.py
impls/rpython/stepA_mal.py

Traverse environments without recursion.  Unwrap the key once. Do not wrap DEBUG-EVAL on each evaluation.
Spare two intermediate MalLists for the 'do' special form.

rpython: simplify and probably remove a performance bottleneck

---

impls/jq/docs/impl-notes.md

re https://github.com/kanaka/mal/pull/685#issuecomment-2397019088, adds a design/impl doc.
@kanaka @asarhaddon: please let me know if I missed anything or if there's anything you'd like me to go into more detail about.

jq: Add some design/implementation documentation

---

impls/fantom/src/mallib/fan/env.fan
impls/fantom/src/step2_eval/fan/main.fan
impls/fantom/src/step3_env/fan/main.fan
impls/fantom/src/step4_if_fn_do/fan/main.fan
impls/fantom/src/step5_tco/fan/main.fan
impls/fantom/src/step6_file/fan/main.fan
impls/fantom/src/step7_quote/fan/main.fan
impls/fantom/src/step8_macros/fan/main.fan
impls/fantom/src/step9_try/fan/main.fan
impls/fantom/src/stepA_mal/fan/main.fan

Various trivial changes minimizing the diff between steps. Hence, this commit should be reviewed with git -b.
Change the type of the key argument in env.{get,set} from MAL symbol to fantom Str.
Return null instead of raising an exception.
Both changes help DEBUG-EVAL.
For readability, merge env.find into env.get.

fantom: merge eval_ast and macroexpand into EVAL, implement DEBUG-EVAL

---

impls/vbs/core.vbs
impls/vbs/env.vbs
impls/vbs/step2_eval.vbs
impls/vbs/step3_env.vbs
impls/vbs/step4_if_fn_do.vbs
impls/vbs/step5_tco.vbs
impls/vbs/step6_file.vbs
impls/vbs/step7_quote.vbs
impls/vbs/step8_macros.vbs
impls/vbs/step9_try.vbs
impls/vbs/stepA_mal.vbs
impls/vbs/types.vbs

Eval_ast was already reserved to lists.
env.vbs: rewrite env.get with a string argument and without exception because this is convenient for DEBUG-EVAL.
types.vbs: after a macro expansion, evaluate with TCO.

vbs: merge {macro,quasiquote}expand into EVAL, add DEBUG-EVAL

---

impls/io/step2_eval.io
impls/io/step3_env.io
impls/io/step4_if_fn_do.io
impls/io/step5_tco.io
impls/io/step6_file.io
impls/io/step7_quote.io
impls/io/step8_macros.io
impls/io/step9_try.io
impls/io/stepA_mal.io

The self-hosted tests fail, for apparently unrelated reasons (the first readline fails in step0). Were they failing before?

io: merge eval_ast into eval, add DEBUG-EVAL

---

impls/haskell/Core.hs
impls/haskell/Env.hs
impls/haskell/Makefile
impls/haskell/Readline.hs
impls/haskell/Types.hs
impls/haskell/run
impls/haskell/step0_repl.hs
impls/haskell/step1_read_print.hs
impls/haskell/step2_eval.hs
impls/haskell/step3_env.hs
impls/haskell/step4_if_fn_do.hs
impls/haskell/step5_tco.hs
impls/haskell/step6_file.hs
impls/haskell/step7_quote.hs
impls/haskell/step8_macros.hs
impls/haskell/step9_try.hs
impls/haskell/stepA_mal.hs

Core, steps: flush standard output before read instead of after print.
Core: merge num_op and cmp_op templates.
Types, Core: use a specific type for map keys.
Fix "get nil :k" (for consistency).
Fix "contains? nil :k" (it was accepting symbols instead of keywords). Remove an unneeded key check in decodeKey.
Move encodeKey from Types.hs to Core.hs.
Env.hs, steps:
Replace the complex and fragile part of c9c504ac creating two sorts of environments with mutable environments, closer to the guide. Move env_apply from Env.hs to stepA_mal.
Makefile:
Remove targets building the last implemented step. Link with readline (explicitly).
Add extra compiler warnings.
Refine the Make dependencies.
run:
Stop requiring bash.
steps:
Import all functions from Env module instead of duplicating the export …

haskell: various small improvements

---

impls/c.2/Makefile
impls/c.2/core.c
impls/c.2/core.h
impls/c.2/env.c
impls/c.2/env.h
impls/c.2/libs/hashmap/hashmap.c
impls/c.2/libs/hashmap/hashmap.h
impls/c.2/libs/linked_list/linked_list.c
impls/c.2/libs/linked_list/linked_list.h
impls/c.2/printer.c
impls/c.2/printer.h
impls/c.2/reader.c
impls/c.2/reader.h
impls/c.2/run
impls/c.2/step0_repl.c
impls/c.2/step1_read_print.c
impls/c.2/step2_eval.c
impls/c.2/step3_env.c
impls/c.2/step4_if_fn_do.c
impls/c.2/step5_tco.c
impls/c.2/step6_file.c
impls/c.2/step7_quote.c
impls/c.2/step8_macros.c
impls/c.2/step9_try.c
impls/c.2/stepA_mal.c
impls/c.2/types.c
impls/c.2/types.h

* Define MalType as a pointer type, instead of an alias for a struct. It is now possible to declare it constant.
* Use macros to avoid lots of code duplication.
* Avoid redundant tests when possible.
* Avoid implicit signed/unsigned conversions.
* Use the const modifier whenever possible.
* Move private forward declarations from .h to .c, and forward declarations on the top of the .c.
Makefile:
enable more warnings avoid recompiling each .o for each step fix .PHONY usage
core.c:
Link mal_list/vector/hash_map directly to make_*. Move mal_readline from stepA (reallocate with GC).
+ - * /: exactly two arguments. =: without memory allocation, stop comparing functions and closures. Stop assuming that nil contains a valid list(first/rest/get). throw: the argument should never be an exception. …

c.2: various improvememts, fix new tests

---

impls/c.2/Makefile
impls/c.2/README
impls/c.2/core.c
impls/c.2/error.h
impls/c.2/hashmap.c
impls/c.2/hashmap.h
impls/c.2/linked_list.c
impls/c.2/linked_list.h
impls/c.2/printer.c
impls/c.2/reader.c
impls/c.2/step2_eval.c
impls/c.2/step3_env.c
impls/c.2/step4_if_fn_do.c
impls/c.2/step5_tco.c
impls/c.2/step6_file.c
impls/c.2/step7_quote.c
impls/c.2/step8_macros.c
impls/c.2/step9_try.c
impls/c.2/stepA_mal.c
impls/c.2/types.c
impls/c.2/types.h
impls/c.2/vector.c
impls/c.2/vector.h

Compute hashes at most once.
Recognize forms with a hash instead of a sequence of string comparisons.

c.2: improve performance
