kanaka/mal

- bash/Makefile
- bash/step0_repl.sh
- bash/step1_read_print.sh
- bash/step2_eval.sh
- bash/step3_env.sh
- bash/step4_if_fn_do.sh
- bash/step5_tco.sh
- bash/step6_file.sh
- bash/step7_quote.sh
- bash/step8_macros.sh
- bash/step9_try.sh
- bash/stepA_interop.sh
- Now works on Macs with Bash4 from homebrew
> bash: use env in shebang

- tests/step5_tco.mal
Hi there, just fixing an extra parenthesis. 
PS: This thing is very addictive :)
> Removed extra parenthesis in tests for step5

- nim/core.nim
- nim/env.nim
- nim/nim.cfg
- nim/step2_eval.nim
- nim/step3_env.nim
- nim/step4_if_fn_do.nim
- nim/step5_tco.nim
- nim/step6_file.nim
- nim/step7_quote.nim
- nim/step8_macros.nim
- nim/step9_try.nim
- nim/stepA_mal.nim
Since we're using the Nim devel compiler and it's still not released yet. There was a change in the indexing.
> Adapt to new Nim devel compiler

- .gitignore
- Makefile
- README.md
- erlang/Makefile
- erlang/rebar.config
- erlang/rebar.config.script
- erlang/src/atom.erl
- erlang/src/core.erl
- erlang/src/env.erl
- erlang/src/mal.app.src
- erlang/src/printer.erl
- erlang/src/reader.erl
- erlang/src/step0_repl.erl
- erlang/src/step1_read_print.erl
- erlang/src/step2_eval.erl
- erlang/src/step3_env.erl
- erlang/src/step4_if_fn_do.erl
- erlang/src/step5_tco.erl
- erlang/src/step6_file.erl
- erlang/src/step7_quote.erl
- erlang/src/step8_macros.erl
- erlang/src/step9_try.erl
- erlang/src/stepA_mal.erl
- erlang/src/types.erl
- tests/docker/Dockerfile
Howdy,
This uses Erlang/OTP R17 features (namely maps) so my Dockerfile additions diverge from the norm and build Erlang from source, rather than installing the older package. Also had to install rebar for building (it makes generating the escript executables trivial).
All tests pass including self-hosting.
If I could do it over again, I would have used records for all of the MAL values (e.g. #list{...} instead of {list, ...}). Much too difficult to fix it now though, and since it is finished, nothing would be gained by changing it now.
Thanks so much for this project. It has been terrific fun.
> Erlang implementation of Make-a-Lisp

- process/guide.md
Thank you for writing this guide. The iterative nature of the steps helps a lot in illustrating how to tackle a project like this.
> Clean up typos in section "Step 4: If Fn Do"

- process/guide.md
> minor improvements

- kotlin/src/mal/core.kt
- kotlin/src/mal/step5_tco.kt
- kotlin/src/mal/step6_file.kt
- kotlin/src/mal/step7_quote.kt
- kotlin/src/mal/step8_macros.kt
- kotlin/src/mal/step9_try.kt
- kotlin/src/mal/stepA_mal.kt
Sorry, juuust missed your merge.  Here's some step cleanup.  I'm done for the night, I think things are in decent shape now.
> Kotlin step cleanup

- tests/step5_tco.mal
I believe this addresses https://github.com/kanaka/mal/issues/58
> Added TCO test for mutually recursive functions

- kotlin/Dockerfile
- kotlin/src/mal/core.kt
- kotlin/src/mal/printer.kt
- kotlin/src/mal/step2_eval.kt
- kotlin/src/mal/step3_env.kt
- kotlin/src/mal/step4_if_fn_do.kt
- kotlin/src/mal/step5_tco.kt
- kotlin/src/mal/step6_file.kt
- kotlin/src/mal/step7_quote.kt
- kotlin/src/mal/step8_macros.kt
- kotlin/src/mal/step9_try.kt
- kotlin/src/mal/stepA_mal.kt
I've made a couple refactorings to make dispatching more idiomatic for Kotlin.
> Kotlin refactoring (more idiomatic)

- ps/core.ps
- ps/types.ps
- tests/step9_try.mal
* extract `_keys` and `_hash_map_get` to `types.ps`
* correct sequential types equals - only compare if *both* arguments are sequential
* implement equality for two hash-maps
I'd appreciate a review because it's almost the first postscript code I wrote.
Also added a few (optional) test cases to step9.
> ps: Fix hash equal

- .gitignore
- Makefile
- README.md
- d/Dockerfile
- d/Makefile
- d/env.d
- d/main.di
- d/mal_core.d
- d/printer.d
- d/reader.d
- d/readline.d
- d/step0_repl.d
- d/step1_read_print.d
- d/step2_eval.d
- d/step3_env.d
- d/step4_if_fn_do.d
- d/step5_tco.d
- d/step6_file.d
- d/step7_quote.d
- d/step8_macros.d
- d/step9_try.d
- d/stepA_mal.d
- d/types.d
- tests/step9_try.mal
D (http://dlang.org) implementation - passes all tests and self-hosting tests. It has readline and history support via libreadline.
Tests of step5 are excluded because D is "small" enough to run 10,000 non-tail calls without crashing. At 1,000,000 it crashes fatally.  D has GC, so running an endless tail recursion has constant memory usage (doesn't crash).
During self-hosting I found a bug in my implementation (handling of hash-map with nil values), so I added the relevant test cases to step9 tests (commit 6496cd1d1732efafa1b63ebc2c3cdc3e3e48c347).
> D implementation

- forth/types.fs
> forth: Fix hash-map equality

- elixir/lib/mal/core.ex
> Elixir: Fix nested list/vector equality

- elixir/lib/mal/core.ex
See https://github.com/kanaka/mal/pull/162#issuecomment-178088724 for more information.
> Elixir: Make sure equals for maps has the correct list/vector behavior

- factor/mal/types/types.factor
> factor: Fix nested list/vector/map equality

- ocaml/core.ml
> ocaml: add seq and string?

- cpp/Core.cpp
Here's a cpp implementation of the #166 string ops
> C++ string? & seq implementations

- tcl/core.tcl
- tcl/types.tcl
> tcl: add seq and string?

- d/mal_core.d
- d/types.d
- go/src/core/core.go
- vimscript/core.vim
> d, go, vimscript: add seq and string?

- crystal/core.cr
- cs/core.cs
- fsharp/core.fs
- fsharp/env.fs
- fsharp/node.fs
- lua/core.lua
- perl/core.pm
- perl/types.pm
- vb/core.vb
> cs, fsharp, vb, crystal, lua, perl: add seq and string?

- elixir/lib/mal/core.ex
- erlang/src/core.erl
- erlang/src/types.erl
> elixir, erlang: add seq and string?

- guile/core.scm
- guile/types.scm
- racket/core.rkt
- racket/types.rkt
> guile, racket: add seq and string?

- factor/mal/core/core.factor
> factor: add seq and string?

- .travis.yml
- Makefile
- README.md
- io/Dockerfile
- io/Env.io
- io/Makefile
- io/MalCore.io
- io/MalReader.io
- io/MalReadline.io
- io/MalTypes.io
- io/step0_repl.io
- io/step1_read_print.io
- io/step2_eval.io
- io/step3_env.io
- io/step4_if_fn_do.io
- io/step5_tco.io
- io/step6_file.io
- io/step7_quote.io
- io/step8_macros.io
- io/step9_try.io
- io/stepA_mal.io
Full Mal implementation in [Io language](http://iolanguage.org/).
It all seems to work including self-hosting, but it's very very slow, even compared to slow implementations like vimscript. Specifically code involving macros is slow, with running (or false false false false true) taking several good seconds. I still want to look into that to see if there's some trivial error in that path in the code.
> Io implementation

- process/guide.md
Hi,
I worked through the guide and created an implementation of Mal in Python 3. I mainly wrote it to learn Python, so I guess it's of little interest to you, but along the way I found some typos and such in the guide, which you may be interested in, which is why I'm creating this pull request.
I really enjoyed working through the guide. I learnt a lot, not just about Python, but also about implementing a Lisp interpreter (which turned out to be much less complicated as I had though, BTW.) Thank you very much for writing Mal!
> Several fixes to the guide

- elisp/step2_eval.el
- elisp/step3_env.el
- elisp/step4_if_fn_do.el
- elisp/step5_tco.el
- elisp/step6_file.el
- elisp/step7_quote.el
- elisp/step8_macros.el
- elisp/step9_try.el
- elisp/stepA_mal.el
> Accept empty list literal

- process/guide.md
I bet the phrasing can be improved. Feel free to modify.
> process/guide: add vector and hash-map evaluation in step 2

- .travis.yml
- Makefile
- README.md
- vhdl/.gitignore
- vhdl/Dockerfile
- vhdl/Makefile
- vhdl/core.vhdl
- vhdl/env.vhdl
- vhdl/pkg_readline.vhdl
- vhdl/printer.vhdl
- vhdl/reader.vhdl
- vhdl/run_vhdl.sh
- vhdl/step0_repl.vhdl
- vhdl/step1_read_print.vhdl
- vhdl/step2_eval.vhdl
- vhdl/step3_env.vhdl
- vhdl/step4_if_fn_do.vhdl
- vhdl/step5_tco.vhdl
- vhdl/step6_file.vhdl
- vhdl/step7_quote.vhdl
- vhdl/step8_macros.vhdl
- vhdl/step9_try.vhdl
- vhdl/stepA_mal.vhdl
- vhdl/types.vhdl
Passes all tests and self-hosted mal tests.
Hacks:
* Content of `*ARGV*` is passed through temporary file (see the `run_vhdl.sh` wrapper).
* Integers are 32-bit so `time-ms` returns milliseconds since 2000-01-01.
> Add VHDL implementation

- docs/TODO
- tests/step6_file.mal
Enable a commented-out test in step6.
> tests: Test slurp captures final newline in step6

- README.md
- crystal/core.cr
- crystal/env.cr
- crystal/error.cr
- crystal/reader.cr
- crystal/step5_tco.cr
- crystal/step6_file.cr
- crystal/step7_quote.cr
- crystal/types.cr
Hi,
I fixed the implementation by Crystal for Crystal v0.17.4.
I confirmed all tests passed in my local environment (OS X).
> Crystal: Fix steps for Crystal v0.17.4

- tests/step3_env.mal
- tests/step4_if_fn_do.mal
Encountered problems during self-hosting while implementing in Logo which is by default case insensitive. These tests should allow early discovery of such problems.
> tests: Verify case sensitivity of names and strings

- io/MalCore.io
- io/run
- io/tests/stepA_mal.mal
Implements `io-eval` and provides test cases.
> io: Add interop function io-eval

- elisp/core.el
- elisp/tests/stepA_mal.mal
> Improve elisp-eval to use MAL types

- clisp/core.lisp
- clisp/env.lisp
- clisp/step3_env.lisp
- clisp/step4_if_fn_do.lisp
- clisp/step5_tco.lisp
- clisp/step6_file.lisp
- clisp/step7_quote.lisp
- clisp/step8_macros.lisp
- clisp/step9_try.lisp
- clisp/stepA_mal.lisp
Hi,
I have pushed some updates to the CLISP implementation
1) Fixed a typo in core `/` function which caused some tests to fail
2) Change `env` implementation to use structs instead of classes
Thanks
> Update CLISP implementation

- guile/run
Hi,
I have enabled auto compilation of guile files, the files are store in the `guile/.cache` directory.
Thanks
> Compile guile files before running them

- haskell/Core.hs
- haskell/Types.hs
- haskell/step1_read_print.hs
- haskell/step2_eval.hs
- haskell/step3_env.hs
- haskell/step4_if_fn_do.hs
- haskell/step5_tco.hs
- haskell/step6_file.hs
- haskell/step7_quote.hs
- haskell/step8_macros.hs
- haskell/step9_try.hs
- haskell/stepA_mal.hs
i'm relatively new to Haskell but this should fix https://github.com/kanaka/mal/issues/226.
> support GHC 7.10.1+ : update error handling

- tests/step9_try.mal
I wrote this after getting bitten by this when running step 3 in self-hosted mode.
> Ensure assoc updates maps properly

- php/README.md
- php/readline.php
- php/stepA_mal.php
To test this:
cd php
make mal.php
echo '(prn "Hello world!")' > myscript.mal
ln -s  mal.php myscript.php
php -S 0.0.0.0:8000
Then browse to http://localhost:8000/myscript.php and you should see "Hello world!" in your browser as the .mal script is run.
> Allow web exec of a .mal file via symlinked php script.

- README.md
- nim/Dockerfile
- nim/core.nim
- nim/step2_eval.nim
- nim/step3_env.nim
- nim/step5_tco.nim
- nim/step6_file.nim
- nim/step7_quote.nim
- nim/step8_macros.nim
- nim/step9_try.nim
- nim/stepA_mal.nim
> Update Nim to 0.15.2, clean up compiler warnings

- .gitignore
- .travis.yml
- Makefile
- README.md
- skew/Dockerfile
- skew/Makefile
- skew/core.sk
- skew/env.sk
- skew/printer.sk
- skew/reader.sk
- skew/run
- skew/step0_repl.sk
- skew/step1_read_print.sk
- skew/step2_eval.sk
- skew/step3_env.sk
- skew/step4_if_fn_do.sk
- skew/step5_tco.sk
- skew/step6_file.sk
- skew/step7_quote.sk
- skew/step8_macros.sk
- skew/step9_try.sk
- skew/stepA_mal.sk
- skew/tests/step5_tco.mal
- skew/types.sk
- skew/util.sk
See http://skew-lang.org/ for details on the Skew language. Currently Mal only compiles to Javascript, as there are some issues with the C# backend for Skew (https://github.com/evanw/skew/issues/19).
Tested with Skew 0.7.42.
> Add Skew implementation

- php/interop.php
- php/tests/stepA_mal.mal
Added test for callbacks during interop which is where this failure showed up.
> Fixed erroneous fn* -> native PHP function conversion.

- README.md
- nim/Dockerfile
- tests/docker/Dockerfile
Tested and builds without warnings or errors and runs tests fine.
> Update to Nim 0.17.0

- .travis.yml
- Makefile
- README.md
- gst/Dockerfile
- gst/Makefile
- gst/core.st
- gst/env.st
- gst/func.st
- gst/printer.st
- gst/reader.st
- gst/readline.st
- gst/run
- gst/step0_repl.st
- gst/step1_read_print.st
- gst/step2_eval.st
- gst/step3_env.st
- gst/step4_if_fn_do.st
- gst/step5_tco.st
- gst/step6_file.st
- gst/step7_quote.st
- gst/step8_macros.st
- gst/step9_try.st
- gst/stepA_mal.st
- gst/types.st
- gst/util.st
> Gnu smalltalk implementation

- tests/step4_if_fn_do.mal
- tests/step9_try.mal
Following two errors I found during implementation.
> tests: Add test cases in step4 and step9

- .travis.yml
- Makefile
- README.md
- yorick/Dockerfile
- yorick/Makefile
- yorick/core.i
- yorick/env.i
- yorick/hash.i
- yorick/printer.i
- yorick/reader.i
- yorick/run
- yorick/step0_repl.i
- yorick/step1_read_print.i
- yorick/step2_eval.i
- yorick/step3_env.i
- yorick/step4_if_fn_do.i
- yorick/step5_tco.i
- yorick/step6_file.i
- yorick/step7_quote.i
- yorick/step8_macros.i
- yorick/step9_try.i
- yorick/stepA_mal.i
- yorick/tests/stepA_mal.mal
- yorick/types.i
Passes all tests and self-hosted Mal tests. Interop using `yorick-eval` function (see the specialized stepA tests).
Yorick 2.2.04 installed via `apt-get`; see `yorick/Dockerfile`.
Added Yorick to top-level Makefile, README.md, and .travis.yml .
> Yorick implementation

- .travis.yml
- README.md
- nasm/Dockerfile
- nasm/Makefile
- nasm/README.md
- nasm/core.asm
- nasm/exceptions.asm
- nasm/macros.mac
- nasm/printer.asm
- nasm/reader.asm
- nasm/step0_repl.asm
- nasm/step1_read_print.asm
- nasm/step2_eval.asm
- nasm/step3_env.asm
- nasm/step4_if_fn_do.asm
- nasm/step5_tco.asm
- nasm/step6_file.asm
- nasm/step7_quote.asm
- nasm/step8_macros.asm
- nasm/step9_try.asm
- nasm/stepA_mal.asm
- nasm/system.asm
- nasm/types.asm
- tests/step7_quote.mal
- tests/step9_try.mal
Thank you for putting together this great guide. I had a lot of fun. Perhaps I wouldn't have started if I'd known how much was involved, but glad I did.  
I'm not sure how idiomatic this code is, as it was a learning experience, but I hope it is not to odd. The code is written for Linux, though the only Linux-specific parts are in `system.asm` (233 lines, 8 syscalls). The rest is quite self-contained, with no external dependencies. Includes memory management, string manipulation etc. in `types.asm`. The other non-standard file is `exceptions.asm` which has a simple exception handling implementation.
I added three tests, to catch issues which appeared in self-hosting. These were the ones which seemed like they might be more general; most of the bugs I found were specific to this …
> NASM x86-64 assembly implementation

- README.md
https://github.com/kanaka/mal/pull/320#issuecomment-400014276
> Added README section for projects using mal.

- README.md
I assume this README serves as a wiki for collecting impls.
> Add link to my Rust implementation

- .travis.yml
- Makefile
- README.md
- swift4/Dockerfile
- swift4/Makefile
- swift4/Sources/core.swift
- swift4/Sources/env.swift
- swift4/Sources/printer.swift
- swift4/Sources/reader.swift
- swift4/Sources/step0_repl/main.swift
- swift4/Sources/step1_read_print/main.swift
- swift4/Sources/step2_eval/main.swift
- swift4/Sources/step3_env/main.swift
- swift4/Sources/step4_if_fn_do/main.swift
- swift4/Sources/step5_tco/main.swift
- swift4/Sources/step6_file/main.swift
- swift4/Sources/step7_quote/main.swift
- swift4/Sources/step8_macros/main.swift
- swift4/Sources/step9_try/main.swift
- swift4/Sources/stepA_mal/main.swift
- swift4/Sources/types.swift
- swift4/run
Here's a swift4 implement. The dockerfile and makefile are from ./swift.
7 tests about metadata on collections not passed.
> Add swift4 implement

- process/guide.md
- tests/step6_file.mal
Hello.  Here are a few small fixes that don't seem to be worth a pull request each.
> Minor doc/test fixes

- tests/step7_quote.mal
- tests/step8_macros.mal
You might like these tests that I've written to expose bugs in my own implementations. I'm submitting these as a separate PR because there's a danger the bugs will turn out to exist in other implementations too.
> A couple of extra tests

- d/Dockerfile
- d/Makefile
- d/env.d
- d/mal_core.d
- d/reader.d
- d/readline.d
- d/step2_eval.d
- d/step3_env.d
- d/step4_if_fn_do.d
- d/step5_tco.d
- d/step6_file.d
- d/step7_quote.d
- d/step8_macros.d
- d/step9_try.d
- d/stepA_mal.d
- d/types.d
- Work around a D bug to get exception handling going
- Fix imports
- Modernize pointer downcasts
> D: Get the code to compile with all three current d compilers

- vala/Makefile
- vala/README.md
- vala/core.vala
- vala/env.vala
- vala/gc.vala
- vala/printer.vala
- vala/reader.vala
- vala/step1_read_print.vala
- vala/step2_eval.vala
- vala/step3_env.vala
- vala/step4_if_fn_do.vala
- vala/step5_tco.vala
- vala/step6_file.vala
- vala/step7_quote.vala
- vala/step8_macros.vala
- vala/step9_try.vala
- vala/stepA_mal.vala
- vala/types.vala
This patch series tidies up various parts of the Vala implementation, of which the most important is that I've added a garbage collector, fixing the memory leak @kanaka pointed out in #368.
> Vala fixes

- crystal/reader.cr
- cs/reader.cs
- es6/reader.mjs
Here are three more fixes for #359. I've got Docker working, which makes testing obscure languages easier.
> cs, crystal, es6: Detect more unterminated strings.

- tests/step4_if_fn_do.mal
Detected while testing to rewrite `let*` with `fn*`.
> Test mutual recursion in let*

- lib/alias-hacks.mal
- tests/lib/alias-hacks.mal
@kanaka @asarhaddon your feedback appreciated.
> Added alias hacks from frock to lib.

- README.md
- python/tests/stepA_mal.mal
These are an assortment of pedantic corrections to the README file and one comment.
> Minor documentation and comment fixes

- ocaml/reader.ml
> ocaml: Fix reading of unterminated strings that happen to end with '"'.

- vhdl/reader.vhdl
> vhdl: Fix reading of unterminated strings that happen to end with '"'.

- rust/core.rs
- rust/env.rs
- rust/printer.rs
- rust/reader.rs
- rust/step0_repl.rs
- rust/step1_read_print.rs
- rust/step2_eval.rs
- rust/step3_env.rs
- rust/step4_if_fn_do.rs
- rust/step5_tco.rs
- rust/step6_file.rs
- rust/step7_quote.rs
- rust/step8_macros.rs
- rust/step9_try.rs
- rust/stepA_mal.rs
- rust/types.rs
Use rustfmt instead of hardcoded vim instructions.
> rust: rustfmt

- README.md
I moved the sourcecode back to GitHub <3
> Link to malcc on GitHub

- python.2/Dockerfile
Match other Dockerfiles to re-use layers.
> Standardize python.2 dockerfile

- README.md
Related: https://github.com/chr15m/flk
> Add reference to flk

- README.md
`npm update` is used to update the deps use `npm install` instead
> npm update should be npm install

- .travis.yml
- Makefile
- README.md
- zig/Dockerfile
- zig/Makefile
- zig/build.zig
- zig/core.zig
- zig/env.zig
- zig/error.zig
- zig/hmap.zig
- zig/linked_list.zig
- zig/logging_alloc.zig
- zig/printer.zig
- zig/reader.zig
- zig/readline.zig
- zig/run
- zig/step0_repl.zig
- zig/step1_read_print.zig
- zig/step2_eval.zig
- zig/step3_env.zig
- zig/step4_if_fn_do.zig
- zig/step5_tco.zig
- zig/step6_file.zig
- zig/step7_quote.zig
- zig/step8_macros.zig
- zig/step9_try.zig
- zig/stepA_mal.zig
- zig/types.zig
- zig/utils.zig
This is preliminary Zig implementation. There are a number of things I'd love to work on further, in particular performance and memory management, but I wanted to push it before the winter holidays. Fair warning that I used this as a project to get familiar with Zig, so there is probably a lot that can be improved upon here (and hopefully I'll be able to make some of those improvements in the coming months).
Seems to pass Docker tests locally, but no doubt will take a few rounds to satisfy the CI tests.
> Zig implementation

- README.md
- nim/Dockerfile
- nim/core.nim
- nim/printer.nim
- nim/reader.nim
- nim/step2_eval.nim
- nim/step3_env.nim
- nim/step4_if_fn_do.nim
- nim/step5_tco.nim
- nim/step6_file.nim
- nim/step7_quote.nim
- nim/step8_macros.nim
- nim/step9_try.nim
- nim/stepA_mal.nim
- nim/types.nim
Will wait for the CI to see what breaks.
> Fix Nim version for Nim 1.0.4

- runtest.py
adds a `--crlf` switch to runtest.py
> issue #491

- jq/env.jq
- jq/rts.py
- jq/step6_file.jq
- jq/step7_quote.jq
- jq/step8_macros.jq
- jq/step9_try.jq
- jq/stepA_mal.jq
Legacy code, just sitting there...
> [jq impl] fix atoms not leaking out of let* (related to pr #493)

- tests/step6_file.mal
> Add test for atoms "leaking" out of let* binds

- process/guide.md
I corrected "you implementation" to "your implementation".
> Correct a trivial typographical error in the guide

- impls/ps/step9_try.ps
- impls/ps/stepA_mal.ps
Here's a proposed fix for the bug in the PostScript implementation exposed by #508. The explanation in the commit message is substantially longer then the commit itself.
> ps: Fix handling of exceptions thrown from `catch*` clause

- impls/jq/step3_env.jq
- impls/jq/step4_if_fn_do.jq
Explicit state is such a pain :)
> Jq: Fix our share of #513

- impls/vimscript/types.vim
Fix soft failure in tests of stepA.
> vimscript: defmacro! doesn't modify existing functions

- impls/vhdl/step8_macros.vhdl
- impls/vhdl/step9_try.vhdl
- impls/vhdl/stepA_mal.vhdl
Fix a soft failure in vhdl stepA tests.
> vhdl: Fix defmacro! so it doesn't modify existing functions

- .github/workflows/main.yml
- .travis_test.sh
Proposal switch pipeline to github actions:
Reason: travis take to long time to finish.
Problems: xcode < 10 has no support, I had success only with switft 5 impls.
> feat: github actions pipeline

- process/guide.md
I'm pretty sure this is a typo at least.
> fix typo in guide.md step 7

- .travis.yml
- Makefile
- README.md
- impls/prolog/Dockerfile
- impls/prolog/Makefile
- impls/prolog/core.pl
- impls/prolog/env.pl
- impls/prolog/printer.pl
- impls/prolog/reader.pl
- impls/prolog/run
- impls/prolog/step0_repl.pl
- impls/prolog/step1_read_print.pl
- impls/prolog/step2_eval.pl
- impls/prolog/step3_env.pl
- impls/prolog/step4_if_fn_do.pl
- impls/prolog/step6_file.pl
- impls/prolog/step7_quote.pl
- impls/prolog/step8_macros.pl
- impls/prolog/step9_try.pl
- impls/prolog/stepA_mal.pl
- impls/prolog/tests/stepA_mal.mal
- impls/prolog/types.pl
- impls/prolog/utils.pl
- impls/tests/stepA_mal.mal
with, in stepA_mal.mal, a new way to pass all test and break
self-hosting nevertheless.
> New SWI-prolog implementation

- impls/tests/step9_try.mal
Self-hosting is not requiring this anymore.
> Move step9 test of map as exceptions from deferrable to optional

- impls/mal/step3_env.mal
- impls/mal/step4_if_fn_do.mal
- impls/mal/step6_file.mal
- impls/mal/step7_quote.mal
- impls/mal/step8_macros.mal
- impls/mal/step9_try.mal
- impls/mal/stepA_mal.mal
I'm trying to debug my step A self hosting, and I noticed that these debugging comments were wrong.
> fixed mal implementation debugging comments

- impls/mal/core.mal
- impls/mal/step4_if_fn_do.mal
- impls/mal/step6_file.mal
- impls/mal/step7_quote.mal
- impls/mal/step8_macros.mal
- impls/mal/step9_try.mal
- impls/mal/stepA_mal.mal
This simplifies a bit previous steps and prepares a future merge
request removing the macro? exception.
> Reduce core_ns in self hosting to a list of symbols

- impls/rexx/Dockerfile
- impls/rexx/run
- impls/rexx/step2_eval.rexx
- impls/rexx/step3_env.rexx
- impls/rexx/step4_if_fn_do.rexx
- impls/rexx/step5_tco.rexx
- impls/rexx/step6_file.rexx
- impls/rexx/step7_quote.rexx
- impls/rexx/step8_macros.rexx
- impls/rexx/step9_try.rexx
- impls/rexx/stepA_mal.rexx
- impls/rexx/types.rexx
> Merge eval_ast and eval in rexx

- impls/matlab/Dockerfile
- impls/matlab/Env.m
- impls/matlab/run
- impls/matlab/step2_eval.m
- impls/matlab/step3_env.m
- impls/matlab/step4_if_fn_do.m
- impls/matlab/step5_tco.m
- impls/matlab/step6_file.m
- impls/matlab/step7_quote.m
- impls/matlab/step8_macros.m
- impls/matlab/step9_try.m
- impls/matlab/stepA_mal.m
> Matlab: merge eval_ast into eval

- impls/xslt/Dockerfile
- impls/xslt/step2_eval.inc.xslt
- impls/xslt/step3_env.inc.xslt
- impls/xslt/step4_if_fn_do.inc.xslt
- impls/xslt/step6_file.inc.xslt
- impls/xslt/step7_quote.inc.xslt
- impls/xslt/step8_macros.inc.xslt
- impls/xslt/step9_try.inc.xslt
- impls/xslt/stepA_mal.inc.xslt
The soft-failure in step8 (macros use closures) was already present.
@alimpfard You may want to take a look at it.
> Xslt: merge eval_ast, debug-eval, reduce diff between steps

- impls/chuck/step2_eval.ck
- impls/chuck/step3_env.ck
- impls/chuck/step4_if_fn_do.ck
- impls/chuck/step5_tco.ck
- impls/chuck/step6_file.ck
- impls/chuck/step7_quote.ck
- impls/chuck/step8_macros.ck
- impls/chuck/step9_try.ck
- impls/chuck/stepA_mal.ck
DEBUG-EVAL was already implemented.
Also fix a mutation by defmacro!.
> chuck: merge eval_ast and macroexpand into EVAL

- impls/swift3/Sources/env.swift
- impls/swift3/Sources/step2_eval/main.swift
- impls/swift3/Sources/step3_env/main.swift
- impls/swift3/Sources/step4_if_fn_do/main.swift
- impls/swift3/Sources/step5_tco/main.swift
- impls/swift3/Sources/step6_file/main.swift
- impls/swift3/Sources/step7_quote/main.swift
- impls/swift3/Sources/step8_macros/main.swift
- impls/swift3/Sources/step9_try/main.swift
- impls/swift3/Sources/stepA_mal/main.swift
- impls/swift4/Sources/step2_eval/main.swift
- impls/swift4/Sources/step3_env/main.swift
- impls/swift4/Sources/step4_if_fn_do/main.swift
- impls/swift4/Sources/step5_tco/main.swift
- impls/swift4/Sources/step6_file/main.swift
- impls/swift4/Sources/step7_quote/main.swift
- impls/swift4/Sources/step8_macros/main.swift
- impls/swift4/Sources/step9_try/main.swift
- impls/swift4/Sources/stepA_mal/main.swift
swift3/stepA: print *host-language*
swift4: reduce differences between steps in spacing, ordering and so on.
swift4/step5: remove a large comment containing non-printable characters
> swift[34]: merge eval_ast and macroexpand into EVAL, add DEBUG-EVAL
